/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_gestion_Hotel (void);
GtkWidget* create_gestio_Vol (void);
GtkWidget* create_catalogue (void);
