/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *button16;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label75;
  GtkWidget *button15;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label74;
  GtkWidget *button17;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label76;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (acceuil, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));
  gtk_window_set_position (GTK_WINDOW (acceuil), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 376, 152);
  gtk_widget_set_size_request (button2, 168, 72);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Gestion Hotel"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 376, 264);
  gtk_widget_set_size_request (button1, 168, 72);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Gestion Vol"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed1), button16, 376, 384);
  gtk_widget_set_size_request (button16, 168, 72);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button16), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Gestion Voiture"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox16), label75, FALSE, FALSE, 0);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed1), button15, 376, 496);
  gtk_widget_set_size_request (button15, 168, 72);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button15), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("Gestion Excursion"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox15), label74, FALSE, FALSE, 0);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed1), button17, 48, 40);
  gtk_widget_set_size_request (button17, 168, 72);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button17), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Consulter Catalogue"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox17), label76, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_AcceuilgestionHotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_AcceuilgestionVol_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_AcceuiCatalogue_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, button2, "button2");
  GLADE_HOOKUP_OBJECT (acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (acceuil, label2, "label2");
  GLADE_HOOKUP_OBJECT (acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (acceuil, label1, "label1");
  GLADE_HOOKUP_OBJECT (acceuil, button16, "button16");
  GLADE_HOOKUP_OBJECT (acceuil, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (acceuil, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (acceuil, image16, "image16");
  GLADE_HOOKUP_OBJECT (acceuil, label75, "label75");
  GLADE_HOOKUP_OBJECT (acceuil, button15, "button15");
  GLADE_HOOKUP_OBJECT (acceuil, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (acceuil, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (acceuil, image15, "image15");
  GLADE_HOOKUP_OBJECT (acceuil, label74, "label74");
  GLADE_HOOKUP_OBJECT (acceuil, button17, "button17");
  GLADE_HOOKUP_OBJECT (acceuil, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (acceuil, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (acceuil, image17, "image17");
  GLADE_HOOKUP_OBJECT (acceuil, label76, "label76");

  return acceuil;
}

GtkWidget*
create_gestion_Hotel (void)
{
  GtkWidget *gestion_Hotel;
  GtkWidget *fixed2;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *calendar1;
  GtkWidget *calendar2;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label15;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label7;
  GtkWidget *combobox1;
  GtkWidget *label10;
  GtkWidget *label16;
  GtkWidget *fixed4;
  GtkWidget *entry2;
  GtkWidget *label18;
  GtkWidget *entry3;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label21;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *label24;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *label17;
  GtkWidget *combobox2;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *label25;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label23;
  GtkWidget *label28;
  GtkWidget *fixed8;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview3;
  GtkWidget *label63;
  GtkWidget *entry7;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *button13;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label67;
  GtkWidget *label62;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;

  gestion_Hotel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_Hotel, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (gestion_Hotel), _("Gestion Hotel"));
  gtk_window_set_position (GTK_WINDOW (gestion_Hotel), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (gestion_Hotel), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_Hotel), fixed2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 8);
  gtk_widget_set_size_request (notebook1, 1016, 640);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 272, 112);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1, 248, 200);
  gtk_widget_set_size_request (calendar1, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar2, 712, 200);
  gtk_widget_set_size_request (calendar2, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 312, 408);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 312, 472);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  label5 = gtk_label_new (_("Date d'admission : "));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 72, 256);
  gtk_widget_set_size_request (label5, 128, 48);

  label6 = gtk_label_new (_("Date de sortie : "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 560, 248);
  gtk_widget_set_size_request (label6, 128, 48);

  label11 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 64, 104);
  gtk_widget_set_size_request (label11, 80, 48);

  label12 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 64, 464);
  gtk_widget_set_size_request (label12, 128, 48);

  label13 = gtk_label_new (_("Nombre de chambre : "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 64, 400);
  gtk_widget_set_size_request (label13, 144, 48);

  label14 = gtk_label_new (_("Type de chambre : "));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 80, 144);
  gtk_widget_set_size_request (label14, 128, 48);

  label8 = gtk_label_new (_("<span foreground=\"red\"><b>Hotel existant!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 320, 24);
  gtk_widget_set_size_request (label8, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  label9 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir nom !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 440, 88);
  gtk_widget_set_size_request (label9, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label15 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir type de chambre !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 440, 128);
  gtk_widget_set_size_request (label15, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed3), button5, 80, 528);
  gtk_widget_set_size_request (button5, 96, 53);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 272, 152);
  gtk_widget_set_size_request (combobox1, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Simple"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Double"));

  label10 = gtk_label_new (_("<span foreground=\"blue\"><i>Hotel ajout\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 40, 24);
  gtk_widget_set_size_request (label10, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label16 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label16);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed4), entry2, 792, 248);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label18 = gtk_label_new (_("Date d'admission : "));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 664, 240);
  gtk_widget_set_size_request (label18, 128, 48);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 792, 312);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label19 = gtk_label_new (_("Date de sortie : "));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 664, 304);
  gtk_widget_set_size_request (label19, 128, 48);

  label20 = gtk_label_new (_("Nombre de chambre : "));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 648, 368);
  gtk_widget_set_size_request (label20, 144, 48);

  spinbutton3_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 832, 376);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label21 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 648, 424);
  gtk_widget_set_size_request (label21, 128, 48);

  spinbutton4_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton4, 832, 432);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 0, 88);
  gtk_widget_set_size_request (scrolledwindow1, 584, 384);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 584, 384);

  label24 = gtk_label_new (_("Modifier l'Hotel : "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 648, 104);
  gtk_widget_set_size_request (label24, 152, 48);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 208, 512);
  gtk_widget_set_size_request (button6, 104, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  label17 = gtk_label_new (_("Type de chambre : "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 664, 176);
  gtk_widget_set_size_request (label17, 128, 48);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2, 792, 184);
  gtk_widget_set_size_request (combobox2, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Simple"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Double"));

  label27 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner un hotel !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 0, 16);
  gtk_widget_set_size_request (label27, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label26 = gtk_label_new (_("<span foreground=\"blue\"><i>Hotel modifi\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 664, 32);
  gtk_widget_set_size_request (label26, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label25 = gtk_label_new ("");
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 816, 104);
  gtk_widget_set_size_request (label25, 104, 48);

  button7 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed4), button7, 760, 488);
  gtk_widget_set_size_request (button7, 96, 53);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox7), label23, FALSE, FALSE, 0);

  label28 = gtk_label_new (_("Afficher/Supprimer/Modifier"));
  gtk_widget_show (label28);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label28);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed8), scrolledwindow3, 0, 48);
  gtk_widget_set_size_request (scrolledwindow3, 592, 344);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview3);
  gtk_widget_set_size_request (treeview3, 592, 344);

  label63 = gtk_label_new (_("Type de chambre : "));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed8), label63, 600, 152);
  gtk_widget_set_size_request (label63, 128, 48);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed8), entry7, 744, 160);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label64 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir type de chambre !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label64, 656, 72);
  gtk_widget_set_size_request (label64, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  label65 = gtk_label_new (_("<span foreground=\"green\"><b>Resulta(s) trouv\303\251e(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label65, 704, 216);
  gtk_widget_set_size_request (label65, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  label66 = gtk_label_new ("");
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed8), label66, 688, 224);
  gtk_widget_set_size_request (label66, 72, 56);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed8), button13, 752, 360);
  gtk_widget_set_size_request (button13, 96, 53);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button13), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox13), label67, FALSE, FALSE, 0);

  label62 = gtk_label_new (_("Chercher"));
  gtk_widget_show (label62);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label62);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 16, 648);
  gtk_widget_set_size_request (button3, 96, 53);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 888, 648);
  gtk_widget_set_size_request (button4, 96, 53);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_AjouterHotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_SupprimerHotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_ModifierHotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_chercherHotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_gestionHotel_Acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_Hotel, gestion_Hotel, "gestion_Hotel");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label5, "label5");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label8, "label8");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, button5, "button5");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label10, "label10");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label63, "label63");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label64, "label64");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label65, "label65");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label66, "label66");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, button13, "button13");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, image13, "image13");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label67, "label67");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label62, "label62");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, button3, "button3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, button4, "button4");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_Hotel, label4, "label4");

  return gestion_Hotel;
}

GtkWidget*
create_gestio_Vol (void)
{
  GtkWidget *gestio_Vol;
  GtkWidget *fixed5;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label30;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label29;
  GtkWidget *notebook2;
  GtkWidget *fixed6;
  GtkWidget *entry4;
  GtkWidget *calendar3;
  GtkWidget *calendar4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label39;
  GtkWidget *label44;
  GtkWidget *button10;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label45;
  GtkWidget *label38;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label43;
  GtkWidget *label37;
  GtkWidget *label36;
  GtkWidget *combobox3;
  GtkWidget *label42;
  GtkWidget *combobox5;
  GtkWidget *combobox4;
  GtkWidget *label46;
  GtkWidget *fixed7;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label47;
  GtkWidget *label59;
  GtkWidget *label55;
  GtkWidget *label60;
  GtkWidget *button12;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *combobox7;
  GtkWidget *label50;
  GtkWidget *combobox8;
  GtkWidget *combobox6;
  GtkWidget *label61;
  GtkWidget *fixed9;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview4;
  GtkWidget *entry8;
  GtkWidget *label69;
  GtkWidget *button14;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label73;
  GtkWidget *label70;
  GtkWidget *label72;
  GtkWidget *label71;
  GtkWidget *label68;

  gestio_Vol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestio_Vol, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (gestio_Vol), _("Gestion Vols"));
  gtk_window_set_position (GTK_WINDOW (gestio_Vol), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (gestio_Vol), FALSE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (gestio_Vol), fixed5);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed5), button9, 888, 640);
  gtk_widget_set_size_request (button9, 96, 53);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox9), label30, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed5), button8, 16, 640);
  gtk_widget_set_size_request (button8, 96, 53);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox8), label29, FALSE, FALSE, 0);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed5), notebook2, 0, 0);
  gtk_widget_set_size_request (notebook2, 1008, 640);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed6);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed6), entry4, 272, 112);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  calendar3 = gtk_calendar_new ();
  gtk_widget_show (calendar3);
  gtk_fixed_put (GTK_FIXED (fixed6), calendar3, 248, 296);
  gtk_widget_set_size_request (calendar3, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar3),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendar4 = gtk_calendar_new ();
  gtk_widget_show (calendar4);
  gtk_fixed_put (GTK_FIXED (fixed6), calendar4, 712, 296);
  gtk_widget_set_size_request (calendar4, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar4),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton5, 248, 512);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton6, 560, 512);
  gtk_widget_set_size_request (spinbutton6, 56, 27);

  label31 = gtk_label_new (_("Id : "));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 88, 104);
  gtk_widget_set_size_request (label31, 80, 48);

  label32 = gtk_label_new (_("Vols disponible : "));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 72, 496);
  gtk_widget_set_size_request (label32, 136, 56);

  label33 = gtk_label_new (_("Date de depart : "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 80, 376);
  gtk_widget_set_size_request (label33, 128, 48);

  label34 = gtk_label_new (_("Date de retour : "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 552, 376);
  gtk_widget_set_size_request (label34, 128, 48);

  label35 = gtk_label_new (_("Destination : "));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 472, 152);
  gtk_widget_set_size_request (label35, 128, 48);

  label39 = gtk_label_new (_("Depart : "));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 24, 152);
  gtk_widget_set_size_request (label39, 128, 48);

  label44 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed6), label44, 432, 496);
  gtk_widget_set_size_request (label44, 128, 56);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed6), button10, 368, 552);
  gtk_widget_set_size_request (button10, 96, 53);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button10), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox10), label45, FALSE, FALSE, 0);

  label38 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir id !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label38, 440, 88);
  gtk_widget_set_size_request (label38, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label40 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Depart !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label40, 256, 144);
  gtk_widget_set_size_request (label40, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  label41 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Destination  !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label41, 736, 136);
  gtk_widget_set_size_request (label41, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  label43 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Companie !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label43, 280, 192);
  gtk_widget_set_size_request (label43, 256, 80);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label37 = gtk_label_new (_("<span foreground=\"red\"><b>Vol existe d\303\251ja !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 320, 24);
  gtk_widget_set_size_request (label37, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label36 = gtk_label_new (_("<span foreground=\"blue\"><i>Vol ajout\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 40, 24);
  gtk_widget_set_size_request (label36, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox3, 144, 160);
  gtk_widget_set_size_request (combobox3, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Algerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Marroc"));

  label42 = gtk_label_new (_("Compagnie : "));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed6), label42, 24, 208);
  gtk_widget_set_size_request (label42, 128, 48);

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox5, 144, 216);
  gtk_widget_set_size_request (combobox5, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Tunisair"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Nouvelair"));

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox4, 600, 160);
  gtk_widget_set_size_request (combobox4, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Algerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Marroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Etat-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Italie"));

  label46 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label46);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label46);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed7);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed7), entry5, 792, 248);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed7), entry6, 792, 296);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton7, 832, 344);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  spinbutton8_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton8, 832, 392);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow2, 0, 88);
  gtk_widget_set_size_request (scrolledwindow2, 584, 384);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);
  gtk_widget_set_size_request (treeview2, 584, 384);

  label48 = gtk_label_new (_("Depart : "));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed7), label48, 664, 112);
  gtk_widget_set_size_request (label48, 128, 48);

  label49 = gtk_label_new (_("Destination : "));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed7), label49, 664, 152);
  gtk_widget_set_size_request (label49, 128, 48);

  label51 = gtk_label_new (_("Date de depart : "));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed7), label51, 664, 240);
  gtk_widget_set_size_request (label51, 128, 48);

  label52 = gtk_label_new (_("Date de retour : "));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed7), label52, 664, 288);
  gtk_widget_set_size_request (label52, 128, 48);

  label53 = gtk_label_new (_("Vols disponible : "));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed7), label53, 648, 336);
  gtk_widget_set_size_request (label53, 144, 48);

  label54 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed7), label54, 648, 384);
  gtk_widget_set_size_request (label54, 128, 48);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed7), button11, 208, 512);
  gtk_widget_set_size_request (button11, 104, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox11), label47, FALSE, FALSE, 0);

  label59 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner un Vol !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), label59, 0, 16);
  gtk_widget_set_size_request (label59, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  label55 = gtk_label_new (_("Modifier le Vol : "));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed7), label55, 648, 72);
  gtk_widget_set_size_request (label55, 152, 48);

  label60 = gtk_label_new (_("<span foreground=\"blue\"><i>Vol modifi\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), label60, 664, 0);
  gtk_widget_set_size_request (label60, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);

  button12 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed7), button12, 760, 472);
  gtk_widget_set_size_request (button12, 96, 53);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button12), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox12), label56, FALSE, FALSE, 0);

  label57 = gtk_label_new ("");
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed7), label57, 784, 72);
  gtk_widget_set_size_request (label57, 104, 48);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox7, 784, 120);
  gtk_widget_set_size_request (combobox7, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Algerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Marroc"));

  label50 = gtk_label_new (_("Compagnie : "));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed7), label50, 664, 192);
  gtk_widget_set_size_request (label50, 128, 48);

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox8, 784, 200);
  gtk_widget_set_size_request (combobox8, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Tunisair"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Nouvelair"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox6, 784, 160);
  gtk_widget_set_size_request (combobox6, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Algerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Marroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Etat-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Italie"));

  label61 = gtk_label_new (_("Afficher/Supprimer/Modifier"));
  gtk_widget_show (label61);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label61);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed9);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_fixed_put (GTK_FIXED (fixed9), scrolledwindow4, 0, 48);
  gtk_widget_set_size_request (scrolledwindow4, 592, 344);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview4);
  gtk_widget_set_size_request (treeview4, 592, 344);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed9), entry8, 744, 160);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label69 = gtk_label_new (_("Companie : "));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed9), label69, 600, 152);
  gtk_widget_set_size_request (label69, 128, 48);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed9), button14, 752, 360);
  gtk_widget_set_size_request (button14, 96, 53);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button14), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox14), label73, FALSE, FALSE, 0);

  label70 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Companie !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), label70, 656, 72);
  gtk_widget_set_size_request (label70, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label70), TRUE);

  label72 = gtk_label_new (_("<span foreground=\"green\"><b>Resulta(s) trouv\303\251e(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), label72, 704, 216);
  gtk_widget_set_size_request (label72, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label72), TRUE);

  label71 = gtk_label_new ("");
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed9), label71, 688, 224);
  gtk_widget_set_size_request (label71, 72, 56);

  label68 = gtk_label_new (_("Chercher"));
  gtk_widget_show (label68);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label68);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_gestionVol_Acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_AjouterVol_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_SupprimerVol_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_ModifierVol_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_chercherVolclicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestio_Vol, gestio_Vol, "gestio_Vol");
  GLADE_HOOKUP_OBJECT (gestio_Vol, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestio_Vol, button9, "button9");
  GLADE_HOOKUP_OBJECT (gestio_Vol, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gestio_Vol, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gestio_Vol, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label30, "label30");
  GLADE_HOOKUP_OBJECT (gestio_Vol, button8, "button8");
  GLADE_HOOKUP_OBJECT (gestio_Vol, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestio_Vol, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestio_Vol, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestio_Vol, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (gestio_Vol, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestio_Vol, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (gestio_Vol, calendar3, "calendar3");
  GLADE_HOOKUP_OBJECT (gestio_Vol, calendar4, "calendar4");
  GLADE_HOOKUP_OBJECT (gestio_Vol, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (gestio_Vol, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label31, "label31");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label32, "label32");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label39, "label39");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label44, "label44");
  GLADE_HOOKUP_OBJECT (gestio_Vol, button10, "button10");
  GLADE_HOOKUP_OBJECT (gestio_Vol, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (gestio_Vol, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (gestio_Vol, image10, "image10");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label45, "label45");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label38, "label38");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label40, "label40");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label41, "label41");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label43, "label43");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label37, "label37");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label36, "label36");
  GLADE_HOOKUP_OBJECT (gestio_Vol, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label42, "label42");
  GLADE_HOOKUP_OBJECT (gestio_Vol, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (gestio_Vol, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label46, "label46");
  GLADE_HOOKUP_OBJECT (gestio_Vol, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (gestio_Vol, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (gestio_Vol, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (gestio_Vol, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (gestio_Vol, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (gestio_Vol, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gestio_Vol, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label48, "label48");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label49, "label49");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label51, "label51");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label52, "label52");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label53, "label53");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label54, "label54");
  GLADE_HOOKUP_OBJECT (gestio_Vol, button11, "button11");
  GLADE_HOOKUP_OBJECT (gestio_Vol, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gestio_Vol, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gestio_Vol, image11, "image11");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label47, "label47");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label59, "label59");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label55, "label55");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label60, "label60");
  GLADE_HOOKUP_OBJECT (gestio_Vol, button12, "button12");
  GLADE_HOOKUP_OBJECT (gestio_Vol, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (gestio_Vol, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (gestio_Vol, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label56, "label56");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label57, "label57");
  GLADE_HOOKUP_OBJECT (gestio_Vol, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label50, "label50");
  GLADE_HOOKUP_OBJECT (gestio_Vol, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (gestio_Vol, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label61, "label61");
  GLADE_HOOKUP_OBJECT (gestio_Vol, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (gestio_Vol, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (gestio_Vol, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (gestio_Vol, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label69, "label69");
  GLADE_HOOKUP_OBJECT (gestio_Vol, button14, "button14");
  GLADE_HOOKUP_OBJECT (gestio_Vol, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (gestio_Vol, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (gestio_Vol, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label73, "label73");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label70, "label70");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label72, "label72");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label71, "label71");
  GLADE_HOOKUP_OBJECT (gestio_Vol, label68, "label68");

  return gestio_Vol;
}

GtkWidget*
create_catalogue (void)
{
  GtkWidget *catalogue;
  GtkWidget *fixed10;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview5;
  GtkWidget *scrolledwindow6;
  GtkWidget *treeview6;
  GtkWidget *button22;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label88;
  GtkWidget *button23;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label89;
  GtkWidget *label84;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *label82;

  catalogue = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (catalogue, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (catalogue), _("Catalogue"));
  gtk_window_set_position (GTK_WINDOW (catalogue), GTK_WIN_POS_CENTER);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (catalogue), fixed10);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_fixed_put (GTK_FIXED (fixed10), scrolledwindow5, 0, 104);
  gtk_widget_set_size_request (scrolledwindow5, 472, 400);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview5);
  gtk_widget_set_size_request (treeview5, 300, 200);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_fixed_put (GTK_FIXED (fixed10), scrolledwindow6, 528, 104);
  gtk_widget_set_size_request (scrolledwindow6, 468, 400);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), treeview6);
  gtk_widget_set_size_request (treeview6, 300, 200);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed10), button22, 16, 640);
  gtk_widget_set_size_request (button22, 96, 53);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button22), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox22), label88, FALSE, FALSE, 0);

  button23 = gtk_button_new ();
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed10), button23, 888, 640);
  gtk_widget_set_size_request (button23, 96, 53);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button23), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label89 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label89);
  gtk_box_pack_start (GTK_BOX (hbox23), label89, FALSE, FALSE, 0);

  label84 = gtk_label_new (_("<span foreground=\"red\" size=\"x-large\"><u>En promotion !</u></span> "));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed10), label84, 32, 528);
  gtk_widget_set_size_request (label84, 248, 64);
  gtk_label_set_use_markup (GTK_LABEL (label84), TRUE);

  label90 = gtk_label_new (_("<span foreground=\"red\" size=\"x-large\"><u>En promotion !</u></span>"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed10), label90, 640, 528);
  gtk_widget_set_size_request (label90, 248, 64);
  gtk_label_set_use_markup (GTK_LABEL (label90), TRUE);

  label91 = gtk_label_new (_("<span foreground=\"blue\" size=\"xx-large\"><b>HOTELS</b></span> "));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed10), label91, 32, 24);
  gtk_widget_set_size_request (label91, 248, 64);
  gtk_label_set_use_markup (GTK_LABEL (label91), TRUE);

  label82 = gtk_label_new (_("\n<span foreground=\"blue\" size=\"xx-large\"><b>VOLS</b></span> "));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed10), label82, 656, 16);
  gtk_widget_set_size_request (label82, 248, 64);
  gtk_label_set_use_markup (GTK_LABEL (label82), TRUE);

  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_catalogue_Acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (catalogue, catalogue, "catalogue");
  GLADE_HOOKUP_OBJECT (catalogue, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (catalogue, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (catalogue, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (catalogue, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (catalogue, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (catalogue, button22, "button22");
  GLADE_HOOKUP_OBJECT (catalogue, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (catalogue, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (catalogue, image22, "image22");
  GLADE_HOOKUP_OBJECT (catalogue, label88, "label88");
  GLADE_HOOKUP_OBJECT (catalogue, button23, "button23");
  GLADE_HOOKUP_OBJECT (catalogue, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (catalogue, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (catalogue, image23, "image23");
  GLADE_HOOKUP_OBJECT (catalogue, label89, "label89");
  GLADE_HOOKUP_OBJECT (catalogue, label84, "label84");
  GLADE_HOOKUP_OBJECT (catalogue, label90, "label90");
  GLADE_HOOKUP_OBJECT (catalogue, label91, "label91");
  GLADE_HOOKUP_OBJECT (catalogue, label82, "label82");

  return catalogue;
}

