/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ahmed_windowajoutervoitureprestation (void)
{
  GtkWidget *ahmed_windowajoutervoitureprestation;
  GtkWidget *Ahmed_fixed;
  GtkWidget *Ahmed_entryid;
  GtkWidget *Ahmed_entryprix;
  GtkWidget *ahmed_button_valider_voiture;
  GtkWidget *Ahmed_alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label29;
  GtkWidget *ahmed_button_afficher_voiture;
  GtkWidget *Ahmed_label21;
  GtkWidget *comboboxentrycarrosserie_voiture;
  GtkWidget *Ahmed_labelcarrosserie;
  GtkWidget *Ahmed_labelprix;
  GtkWidget *comboboxentryetat_voiture;
  GtkWidget *ahmed_button_retour_voiture;
  GtkWidget *Ahmed_alignment11;
  GtkWidget *Ahmed_hbox11;
  GtkWidget *Ahmed_image11;
  GtkWidget *Ahmed_label43;
  GtkWidget *label59;
  GtkWidget *ahmed_promotion_voiture;
  GtkWidget *ahmed_entryreductionvoiture;
  GtkWidget *comboboxentrymodele_voiture;
  GtkWidget *Ahmed_labelchoix;
  GtkWidget *label84;
  GtkWidget *Ahmed_labeletat;
  GtkWidget *ahmed_label_ajoutervoiture;
  GtkWidget *comboboxentrymarque_voiture;

  ahmed_windowajoutervoitureprestation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ahmed_windowajoutervoitureprestation), _("Ajouter une voiture"));

  Ahmed_fixed = gtk_fixed_new ();
  gtk_widget_show (Ahmed_fixed);
  gtk_container_add (GTK_CONTAINER (ahmed_windowajoutervoitureprestation), Ahmed_fixed);

  Ahmed_entryid = gtk_entry_new ();
  gtk_widget_show (Ahmed_entryid);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), Ahmed_entryid, 168, 112);
  gtk_widget_set_size_request (Ahmed_entryid, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (Ahmed_entryid), 8226);

  Ahmed_entryprix = gtk_entry_new ();
  gtk_widget_show (Ahmed_entryprix);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), Ahmed_entryprix, 608, 192);
  gtk_widget_set_size_request (Ahmed_entryprix, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (Ahmed_entryprix), 8226);

  ahmed_button_valider_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_valider_voiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), ahmed_button_valider_voiture, 448, 408);
  gtk_widget_set_size_request (ahmed_button_valider_voiture, 112, 32);

  Ahmed_alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (Ahmed_alignment8);
  gtk_container_add (GTK_CONTAINER (ahmed_button_valider_voiture), Ahmed_alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (Ahmed_alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox8), label29, FALSE, FALSE, 0);

  ahmed_button_afficher_voiture = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (ahmed_button_afficher_voiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), ahmed_button_afficher_voiture, 312, 408);
  gtk_widget_set_size_request (ahmed_button_afficher_voiture, 112, 32);

  Ahmed_label21 = gtk_label_new (_("Mod\303\250le :"));
  gtk_widget_show (Ahmed_label21);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), Ahmed_label21, 8, 272);
  gtk_widget_set_size_request (Ahmed_label21, 80, 40);

  comboboxentrycarrosserie_voiture = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrycarrosserie_voiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), comboboxentrycarrosserie_voiture, 168, 352);
  gtk_widget_set_size_request (comboboxentrycarrosserie_voiture, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycarrosserie_voiture), _("Berlin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycarrosserie_voiture), _("Citadine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycarrosserie_voiture), _("Pick-up"));

  Ahmed_labelcarrosserie = gtk_label_new (_("Carrosserie :"));
  gtk_widget_show (Ahmed_labelcarrosserie);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), Ahmed_labelcarrosserie, 8, 352);
  gtk_widget_set_size_request (Ahmed_labelcarrosserie, 104, 40);

  Ahmed_labelprix = gtk_label_new (_("Prix unitaire / jour :"));
  gtk_widget_show (Ahmed_labelprix);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), Ahmed_labelprix, 440, 192);
  gtk_widget_set_size_request (Ahmed_labelprix, 160, 40);

  comboboxentryetat_voiture = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryetat_voiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), comboboxentryetat_voiture, 608, 112);
  gtk_widget_set_size_request (comboboxentryetat_voiture, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryetat_voiture), _("Bon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryetat_voiture), _("Moyen"));

  ahmed_button_retour_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_retour_voiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), ahmed_button_retour_voiture, 32, 0);
  gtk_widget_set_size_request (ahmed_button_retour_voiture, 112, 32);

  Ahmed_alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (Ahmed_alignment11);
  gtk_container_add (GTK_CONTAINER (ahmed_button_retour_voiture), Ahmed_alignment11);

  Ahmed_hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (Ahmed_hbox11);
  gtk_container_add (GTK_CONTAINER (Ahmed_alignment11), Ahmed_hbox11);

  Ahmed_image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (Ahmed_image11);
  gtk_box_pack_start (GTK_BOX (Ahmed_hbox11), Ahmed_image11, FALSE, FALSE, 0);

  Ahmed_label43 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (Ahmed_label43);
  gtk_box_pack_start (GTK_BOX (Ahmed_hbox11), Ahmed_label43, FALSE, FALSE, 0);

  label59 = gtk_label_new (_("Made with <3 by Ahmed"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), label59, 632, 472);
  gtk_widget_set_size_request (label59, 224, 16);

  ahmed_promotion_voiture = gtk_label_new (_("R\303\251duction (en %) :"));
  gtk_widget_show (ahmed_promotion_voiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), ahmed_promotion_voiture, 448, 288);
  gtk_widget_set_size_request (ahmed_promotion_voiture, 136, 24);

  ahmed_entryreductionvoiture = gtk_entry_new ();
  gtk_widget_show (ahmed_entryreductionvoiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), ahmed_entryreductionvoiture, 608, 272);
  gtk_widget_set_size_request (ahmed_entryreductionvoiture, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ahmed_entryreductionvoiture), 8226);

  comboboxentrymodele_voiture = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrymodele_voiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), comboboxentrymodele_voiture, 168, 272);
  gtk_widget_set_size_request (comboboxentrymodele_voiture, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodele_voiture), _("S\303\251rie_5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodele_voiture), _("Fabia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodele_voiture), _("LandCruiser"));

  Ahmed_labelchoix = gtk_label_new (_("Marque :"));
  gtk_widget_show (Ahmed_labelchoix);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), Ahmed_labelchoix, 0, 192);
  gtk_widget_set_size_request (Ahmed_labelchoix, 104, 32);

  label84 = gtk_label_new (_("<span foreground=\"chartreuse\"><b>Ajouter une personne :</b></span>"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), label84, 336, 40);
  gtk_widget_set_size_request (label84, 168, 24);
  gtk_label_set_use_markup (GTK_LABEL (label84), TRUE);

  Ahmed_labeletat = gtk_label_new (_("Etat :"));
  gtk_widget_show (Ahmed_labeletat);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), Ahmed_labeletat, 440, 120);
  gtk_widget_set_size_request (Ahmed_labeletat, 48, 24);

  ahmed_label_ajoutervoiture = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (ahmed_label_ajoutervoiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), ahmed_label_ajoutervoiture, 0, 120);
  gtk_widget_set_size_request (ahmed_label_ajoutervoiture, 120, 16);

  comboboxentrymarque_voiture = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrymarque_voiture);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed), comboboxentrymarque_voiture, 168, 192);
  gtk_widget_set_size_request (comboboxentrymarque_voiture, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymarque_voiture), _("BMW"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymarque_voiture), _("Skoda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymarque_voiture), _("Toyota"));

  g_signal_connect ((gpointer) ahmed_button_valider_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_valider_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_afficher_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_afficher_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_retour_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_retour_ajouter_voiture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ahmed_windowajoutervoitureprestation, ahmed_windowajoutervoitureprestation, "ahmed_windowajoutervoitureprestation");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_fixed, "Ahmed_fixed");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_entryid, "Ahmed_entryid");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_entryprix, "Ahmed_entryprix");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, ahmed_button_valider_voiture, "ahmed_button_valider_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_alignment8, "Ahmed_alignment8");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, image8, "image8");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, label29, "label29");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, ahmed_button_afficher_voiture, "ahmed_button_afficher_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_label21, "Ahmed_label21");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, comboboxentrycarrosserie_voiture, "comboboxentrycarrosserie_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_labelcarrosserie, "Ahmed_labelcarrosserie");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_labelprix, "Ahmed_labelprix");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, comboboxentryetat_voiture, "comboboxentryetat_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, ahmed_button_retour_voiture, "ahmed_button_retour_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_alignment11, "Ahmed_alignment11");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_hbox11, "Ahmed_hbox11");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_image11, "Ahmed_image11");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_label43, "Ahmed_label43");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, label59, "label59");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, ahmed_promotion_voiture, "ahmed_promotion_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, ahmed_entryreductionvoiture, "ahmed_entryreductionvoiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, comboboxentrymodele_voiture, "comboboxentrymodele_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_labelchoix, "Ahmed_labelchoix");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, label84, "label84");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, Ahmed_labeletat, "Ahmed_labeletat");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, ahmed_label_ajoutervoiture, "ahmed_label_ajoutervoiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutervoitureprestation, comboboxentrymarque_voiture, "comboboxentrymarque_voiture");

  return ahmed_windowajoutervoitureprestation;
}

GtkWidget*
create_ahmed_windowajoutexcursionprestation (void)
{
  GtkWidget *ahmed_windowajoutexcursionprestation;
  GtkWidget *ahmed_fixed3;
  GtkObject *ahmed_spinbuttonplacedispo_adj;
  GtkWidget *ahmed_spinbuttonplacedispo;
  GtkWidget *entrydestination;
  GtkObject *ahmed_spinbuttonjourdepart_adj;
  GtkWidget *ahmed_spinbuttonjourdepart;
  GtkObject *ahmed_spinbuttomoisdepart_adj;
  GtkWidget *ahmed_spinbuttomoisdepart;
  GtkObject *ahmed_spinbuttonanneedepart_adj;
  GtkWidget *ahmed_spinbuttonanneedepart;
  GtkWidget *ahmed_entrydepart;
  GtkObject *ahmed_spinbuttonjourretour_adj;
  GtkWidget *ahmed_spinbuttonjourretour;
  GtkObject *ahmed_spinbuttonmoisretour_adj;
  GtkWidget *ahmed_spinbuttonmoisretour;
  GtkObject *ahmed_spinbuttonanneeretour_adj;
  GtkWidget *ahmed_spinbuttonanneeretour;
  GtkWidget *entry8;
  GtkWidget *ahmed_button_afficher_excursion;
  GtkWidget *ahmed_button_valider_excursion;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label52;
  GtkWidget *ahmed_label84;
  GtkWidget *labelplacedispo;
  GtkWidget *labelprix;
  GtkWidget *labelretour;
  GtkWidget *label37;
  GtkWidget *label39;
  GtkWidget *labellieu;
  GtkWidget *labelannee;
  GtkWidget *labelmois;
  GtkWidget *labeldepart;
  GtkWidget *labeljour;
  GtkWidget *label38;
  GtkWidget *ahmed_button_retour_excursion;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label53;
  GtkWidget *ahmed_entryidexcursion;
  GtkWidget *label19;
  GtkWidget *ahmed_label85;
  GtkWidget *labelajouterreservation;

  ahmed_windowajoutexcursionprestation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ahmed_windowajoutexcursionprestation), _("window ajout excursion prestation"));

  ahmed_fixed3 = gtk_fixed_new ();
  gtk_widget_show (ahmed_fixed3);
  gtk_container_add (GTK_CONTAINER (ahmed_windowajoutexcursionprestation), ahmed_fixed3);

  ahmed_spinbuttonplacedispo_adj = gtk_adjustment_new (40, 1, 50, 1, 10, 10);
  ahmed_spinbuttonplacedispo = gtk_spin_button_new (GTK_ADJUSTMENT (ahmed_spinbuttonplacedispo_adj), 1, 0);
  gtk_widget_show (ahmed_spinbuttonplacedispo);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_spinbuttonplacedispo, 232, 496);
  gtk_widget_set_size_request (ahmed_spinbuttonplacedispo, 60, 27);

  entrydestination = gtk_entry_new ();
  gtk_widget_show (entrydestination);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), entrydestination, 176, 168);
  gtk_widget_set_size_request (entrydestination, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydestination), 8226);

  ahmed_spinbuttonjourdepart_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  ahmed_spinbuttonjourdepart = gtk_spin_button_new (GTK_ADJUSTMENT (ahmed_spinbuttonjourdepart_adj), 1, 0);
  gtk_widget_show (ahmed_spinbuttonjourdepart);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_spinbuttonjourdepart, 168, 224);
  gtk_widget_set_size_request (ahmed_spinbuttonjourdepart, 60, 27);

  ahmed_spinbuttomoisdepart_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ahmed_spinbuttomoisdepart = gtk_spin_button_new (GTK_ADJUSTMENT (ahmed_spinbuttomoisdepart_adj), 1, 0);
  gtk_widget_show (ahmed_spinbuttomoisdepart);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_spinbuttomoisdepart, 320, 224);
  gtk_widget_set_size_request (ahmed_spinbuttomoisdepart, 60, 27);

  ahmed_spinbuttonanneedepart_adj = gtk_adjustment_new (2019, 2019, 2030, 1, 10, 10);
  ahmed_spinbuttonanneedepart = gtk_spin_button_new (GTK_ADJUSTMENT (ahmed_spinbuttonanneedepart_adj), 1, 0);
  gtk_widget_show (ahmed_spinbuttonanneedepart);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_spinbuttonanneedepart, 488, 224);
  gtk_widget_set_size_request (ahmed_spinbuttonanneedepart, 60, 27);

  ahmed_entrydepart = gtk_entry_new ();
  gtk_widget_show (ahmed_entrydepart);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_entrydepart, 216, 288);
  gtk_widget_set_size_request (ahmed_entrydepart, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ahmed_entrydepart), 8226);

  ahmed_spinbuttonjourretour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  ahmed_spinbuttonjourretour = gtk_spin_button_new (GTK_ADJUSTMENT (ahmed_spinbuttonjourretour_adj), 1, 0);
  gtk_widget_show (ahmed_spinbuttonjourretour);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_spinbuttonjourretour, 152, 368);
  gtk_widget_set_size_request (ahmed_spinbuttonjourretour, 60, 27);

  ahmed_spinbuttonmoisretour_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ahmed_spinbuttonmoisretour = gtk_spin_button_new (GTK_ADJUSTMENT (ahmed_spinbuttonmoisretour_adj), 1, 0);
  gtk_widget_show (ahmed_spinbuttonmoisretour);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_spinbuttonmoisretour, 320, 368);
  gtk_widget_set_size_request (ahmed_spinbuttonmoisretour, 60, 27);

  ahmed_spinbuttonanneeretour_adj = gtk_adjustment_new (2019, 2019, 2030, 1, 10, 10);
  ahmed_spinbuttonanneeretour = gtk_spin_button_new (GTK_ADJUSTMENT (ahmed_spinbuttonanneeretour_adj), 1, 0);
  gtk_widget_show (ahmed_spinbuttonanneeretour);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_spinbuttonanneeretour, 488, 368);
  gtk_widget_set_size_request (ahmed_spinbuttonanneeretour, 60, 27);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), entry8, 232, 440);
  gtk_widget_set_size_request (entry8, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  ahmed_button_afficher_excursion = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (ahmed_button_afficher_excursion);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_button_afficher_excursion, 176, 560);
  gtk_widget_set_size_request (ahmed_button_afficher_excursion, 112, 32);

  ahmed_button_valider_excursion = gtk_button_new ();
  gtk_widget_show (ahmed_button_valider_excursion);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_button_valider_excursion, 344, 560);
  gtk_widget_set_size_request (ahmed_button_valider_excursion, 112, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (ahmed_button_valider_excursion), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox19), label52, FALSE, FALSE, 0);

  ahmed_label84 = gtk_label_new (_("Made with <3 by Ahmed"));
  gtk_widget_show (ahmed_label84);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_label84, 648, 600);
  gtk_widget_set_size_request (ahmed_label84, 208, 16);

  labelplacedispo = gtk_label_new (_("Nombre de place disponible :"));
  gtk_widget_show (labelplacedispo);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labelplacedispo, 8, 496);
  gtk_widget_set_size_request (labelplacedispo, 208, 32);

  labelprix = gtk_label_new (_("Prix unitaire / personne :"));
  gtk_widget_show (labelprix);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labelprix, 0, 456);
  gtk_widget_set_size_request (labelprix, 192, 16);

  labelretour = gtk_label_new (_("Retour :"));
  gtk_widget_show (labelretour);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labelretour, 0, 376);
  gtk_widget_set_size_request (labelretour, 80, 16);

  label37 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), label37, 88, 376);
  gtk_widget_set_size_request (label37, 72, 16);

  label39 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), label39, 408, 376);
  gtk_widget_set_size_request (label39, 80, 16);

  labellieu = gtk_label_new (_("Lieu :"));
  gtk_widget_show (labellieu);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labellieu, 144, 304);
  gtk_widget_set_size_request (labellieu, 64, 16);

  labelannee = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (labelannee);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labelannee, 408, 232);
  gtk_widget_set_size_request (labelannee, 80, 16);

  labelmois = gtk_label_new (_("Mois :"));
  gtk_widget_show (labelmois);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labelmois, 256, 232);
  gtk_widget_set_size_request (labelmois, 56, 16);

  labeldepart = gtk_label_new (_("D\303\251part :"));
  gtk_widget_show (labeldepart);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labeldepart, 8, 224);
  gtk_widget_set_size_request (labeldepart, 80, 32);

  labeljour = gtk_label_new (_("Jour :"));
  gtk_widget_show (labeljour);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labeljour, 88, 232);
  gtk_widget_set_size_request (labeljour, 72, 16);

  label38 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), label38, 256, 376);
  gtk_widget_set_size_request (label38, 56, 16);

  ahmed_button_retour_excursion = gtk_button_new ();
  gtk_widget_show (ahmed_button_retour_excursion);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_button_retour_excursion, 16, 8);
  gtk_widget_set_size_request (ahmed_button_retour_excursion, 112, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (ahmed_button_retour_excursion), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox20), label53, FALSE, FALSE, 0);

  ahmed_entryidexcursion = gtk_entry_new ();
  gtk_widget_show (ahmed_entryidexcursion);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_entryidexcursion, 176, 112);
  gtk_widget_set_size_request (ahmed_entryidexcursion, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ahmed_entryidexcursion), 8226);

  label19 = gtk_label_new (_("Destination :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), label19, 24, 176);
  gtk_widget_set_size_request (label19, 104, 24);

  ahmed_label85 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (ahmed_label85);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), ahmed_label85, 16, 128);
  gtk_widget_set_size_request (ahmed_label85, 112, 16);

  labelajouterreservation = gtk_label_new (_("Ajouter une excusion"));
  gtk_widget_show (labelajouterreservation);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed3), labelajouterreservation, 192, 40);
  gtk_widget_set_size_request (labelajouterreservation, 192, 40);

  g_signal_connect ((gpointer) ahmed_button_afficher_excursion, "clicked",
                    G_CALLBACK (on_ahmed_button_afficher_excursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_valider_excursion, "clicked",
                    G_CALLBACK (on_ahmed_button_valider_excursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_retour_excursion, "clicked",
                    G_CALLBACK (on_ahmed_button_retour_ajouter_excursion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ahmed_windowajoutexcursionprestation, ahmed_windowajoutexcursionprestation, "ahmed_windowajoutexcursionprestation");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_fixed3, "ahmed_fixed3");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_spinbuttonplacedispo, "ahmed_spinbuttonplacedispo");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, entrydestination, "entrydestination");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_spinbuttonjourdepart, "ahmed_spinbuttonjourdepart");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_spinbuttomoisdepart, "ahmed_spinbuttomoisdepart");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_spinbuttonanneedepart, "ahmed_spinbuttonanneedepart");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_entrydepart, "ahmed_entrydepart");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_spinbuttonjourretour, "ahmed_spinbuttonjourretour");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_spinbuttonmoisretour, "ahmed_spinbuttonmoisretour");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_spinbuttonanneeretour, "ahmed_spinbuttonanneeretour");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_button_afficher_excursion, "ahmed_button_afficher_excursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_button_valider_excursion, "ahmed_button_valider_excursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, image19, "image19");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, label52, "label52");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_label84, "ahmed_label84");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labelplacedispo, "labelplacedispo");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labelprix, "labelprix");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labelretour, "labelretour");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, label37, "label37");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, label39, "label39");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labellieu, "labellieu");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labelannee, "labelannee");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labelmois, "labelmois");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labeldepart, "labeldepart");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labeljour, "labeljour");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, label38, "label38");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_button_retour_excursion, "ahmed_button_retour_excursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, image20, "image20");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, label53, "label53");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_entryidexcursion, "ahmed_entryidexcursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, label19, "label19");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, ahmed_label85, "ahmed_label85");
  GLADE_HOOKUP_OBJECT (ahmed_windowajoutexcursionprestation, labelajouterreservation, "labelajouterreservation");

  return ahmed_windowajoutexcursionprestation;
}

GtkWidget*
create_ahmed_windowmenuvoitureprestation (void)
{
  GtkWidget *ahmed_windowmenuvoitureprestation;
  GtkWidget *ahmed_fixed4;
  GtkWidget *ahmed_treeview_main_voiture;
  GtkWidget *ahmed_button_retour_main_voiture;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label28;
  GtkWidget *ahmed_button_ajouter_main_voiture;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label25;
  GtkWidget *ahmed_button_modifier_main_voiture;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label26;
  GtkWidget *ahmed_button_supprimer_main_voiture;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label27;
  GtkWidget *ahmed_entryrecherchevoitureprestation;
  GtkWidget *ahmed_buttoncherchervoitureprestation;
  GtkWidget *image33;
  GtkWidget *ahmed_label79;
  GtkWidget *ahmed_label77;
  GtkWidget *ahmed_label22;
  GtkWidget *image40;

  ahmed_windowmenuvoitureprestation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ahmed_windowmenuvoitureprestation), _("window menu voiture"));

  ahmed_fixed4 = gtk_fixed_new ();
  gtk_widget_show (ahmed_fixed4);
  gtk_container_add (GTK_CONTAINER (ahmed_windowmenuvoitureprestation), ahmed_fixed4);

  ahmed_treeview_main_voiture = gtk_tree_view_new ();
  gtk_widget_show (ahmed_treeview_main_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_treeview_main_voiture, 0, 96);
  gtk_widget_set_size_request (ahmed_treeview_main_voiture, 488, 272);

  ahmed_button_retour_main_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_retour_main_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_button_retour_main_voiture, 16, 16);
  gtk_widget_set_size_request (ahmed_button_retour_main_voiture, 160, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ahmed_button_retour_main_voiture), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox7), label28, FALSE, FALSE, 0);

  ahmed_button_ajouter_main_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_ajouter_main_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_button_ajouter_main_voiture, 24, 400);
  gtk_widget_set_size_request (ahmed_button_ajouter_main_voiture, 112, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ahmed_button_ajouter_main_voiture), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox4), label25, FALSE, FALSE, 0);

  ahmed_button_modifier_main_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_modifier_main_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_button_modifier_main_voiture, 176, 400);
  gtk_widget_set_size_request (ahmed_button_modifier_main_voiture, 112, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ahmed_button_modifier_main_voiture), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox5), label26, FALSE, FALSE, 0);

  ahmed_button_supprimer_main_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_supprimer_main_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_button_supprimer_main_voiture, 328, 400);
  gtk_widget_set_size_request (ahmed_button_supprimer_main_voiture, 112, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (ahmed_button_supprimer_main_voiture), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox6), label27, FALSE, FALSE, 0);

  ahmed_entryrecherchevoitureprestation = gtk_entry_new ();
  gtk_widget_show (ahmed_entryrecherchevoitureprestation);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_entryrecherchevoitureprestation, 536, 112);
  gtk_widget_set_size_request (ahmed_entryrecherchevoitureprestation, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ahmed_entryrecherchevoitureprestation), 8226);

  ahmed_buttoncherchervoitureprestation = gtk_button_new ();
  gtk_widget_show (ahmed_buttoncherchervoitureprestation);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_buttoncherchervoitureprestation, 736, 112);
  gtk_widget_set_size_request (ahmed_buttoncherchervoitureprestation, 36, 32);

  image33 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_container_add (GTK_CONTAINER (ahmed_buttoncherchervoitureprestation), image33);

  ahmed_label79 = gtk_label_new (_("Rechercher selon l'id :"));
  gtk_widget_show (ahmed_label79);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_label79, 528, 96);
  gtk_widget_set_size_request (ahmed_label79, 168, 16);

  ahmed_label77 = gtk_label_new (_("Made with <3 by Ahmed"));
  gtk_widget_show (ahmed_label77);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_label77, 680, 480);
  gtk_widget_set_size_request (ahmed_label77, 192, 32);

  ahmed_label22 = gtk_label_new (_("Menu voiture :"));
  gtk_widget_show (ahmed_label22);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), ahmed_label22, 248, 56);
  gtk_widget_set_size_request (ahmed_label22, 128, 24);

  image40 = create_pixmap (ahmed_windowmenuvoitureprestation, "ahmed_images.jpg");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed4), image40, 512, 160);
  gtk_widget_set_size_request (image40, 304, 200);

  g_signal_connect ((gpointer) ahmed_button_retour_main_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_retour_main_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_ajouter_main_voiture, "clicked",
                    G_CALLBACK (on_ahmed_ajouter_main_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_modifier_main_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_modifier_main_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_supprimer_main_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_supprimer_main_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_buttoncherchervoitureprestation, "clicked",
                    G_CALLBACK (on_ahmed_button_chercher_voiture_prestation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ahmed_windowmenuvoitureprestation, ahmed_windowmenuvoitureprestation, "ahmed_windowmenuvoitureprestation");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_fixed4, "ahmed_fixed4");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_treeview_main_voiture, "ahmed_treeview_main_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_button_retour_main_voiture, "ahmed_button_retour_main_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, image7, "image7");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, label28, "label28");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_button_ajouter_main_voiture, "ahmed_button_ajouter_main_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, image4, "image4");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, label25, "label25");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_button_modifier_main_voiture, "ahmed_button_modifier_main_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, image5, "image5");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, label26, "label26");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_button_supprimer_main_voiture, "ahmed_button_supprimer_main_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, image6, "image6");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, label27, "label27");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_entryrecherchevoitureprestation, "ahmed_entryrecherchevoitureprestation");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_buttoncherchervoitureprestation, "ahmed_buttoncherchervoitureprestation");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, image33, "image33");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_label79, "ahmed_label79");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_label77, "ahmed_label77");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, ahmed_label22, "ahmed_label22");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuvoitureprestation, image40, "image40");

  return ahmed_windowmenuvoitureprestation;
}

GtkWidget*
create_ahmed_windowmenuexcursionprestation (void)
{
  GtkWidget *ahmed_windowmenuexcursionprestation;
  GtkWidget *Ahmed_fixed_w_main_excur;
  GtkWidget *ahmed_treeviewmenuexcursion;
  GtkWidget *Ahmed_label_signa;
  GtkWidget *ahmed_button_modifier_main_excursion;
  GtkWidget *Ahmed_alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label55;
  GtkWidget *ahmed_button_ajouter_main_excursion;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label54;
  GtkWidget *ahmed_button_supp_main_excursion;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label56;
  GtkWidget *ahmed_button_retour_main_excursion;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label57;
  GtkWidget *Ahmed_labelmenuexcursion;

  ahmed_windowmenuexcursionprestation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ahmed_windowmenuexcursionprestation), _("window menu excursion"));

  Ahmed_fixed_w_main_excur = gtk_fixed_new ();
  gtk_widget_show (Ahmed_fixed_w_main_excur);
  gtk_container_add (GTK_CONTAINER (ahmed_windowmenuexcursionprestation), Ahmed_fixed_w_main_excur);

  ahmed_treeviewmenuexcursion = gtk_tree_view_new ();
  gtk_widget_show (ahmed_treeviewmenuexcursion);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed_w_main_excur), ahmed_treeviewmenuexcursion, 40, 120);
  gtk_widget_set_size_request (ahmed_treeviewmenuexcursion, 680, 248);

  Ahmed_label_signa = gtk_label_new (_("Created with <3 by Ahmed"));
  gtk_widget_show (Ahmed_label_signa);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed_w_main_excur), Ahmed_label_signa, 600, 472);
  gtk_widget_set_size_request (Ahmed_label_signa, 209, 25);

  ahmed_button_modifier_main_excursion = gtk_button_new ();
  gtk_widget_show (ahmed_button_modifier_main_excursion);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed_w_main_excur), ahmed_button_modifier_main_excursion, 296, 392);
  gtk_widget_set_size_request (ahmed_button_modifier_main_excursion, 112, 32);

  Ahmed_alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (Ahmed_alignment22);
  gtk_container_add (GTK_CONTAINER (ahmed_button_modifier_main_excursion), Ahmed_alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (Ahmed_alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox22), label55, FALSE, FALSE, 0);

  ahmed_button_ajouter_main_excursion = gtk_button_new ();
  gtk_widget_show (ahmed_button_ajouter_main_excursion);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed_w_main_excur), ahmed_button_ajouter_main_excursion, 144, 392);
  gtk_widget_set_size_request (ahmed_button_ajouter_main_excursion, 112, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (ahmed_button_ajouter_main_excursion), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox21), label54, FALSE, FALSE, 0);

  ahmed_button_supp_main_excursion = gtk_button_new ();
  gtk_widget_show (ahmed_button_supp_main_excursion);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed_w_main_excur), ahmed_button_supp_main_excursion, 448, 392);
  gtk_widget_set_size_request (ahmed_button_supp_main_excursion, 112, 32);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (ahmed_button_supp_main_excursion), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox23), label56, FALSE, FALSE, 0);

  ahmed_button_retour_main_excursion = gtk_button_new ();
  gtk_widget_show (ahmed_button_retour_main_excursion);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed_w_main_excur), ahmed_button_retour_main_excursion, 32, 8);
  gtk_widget_set_size_request (ahmed_button_retour_main_excursion, 112, 32);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (ahmed_button_retour_main_excursion), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox24), label57, FALSE, FALSE, 0);

  Ahmed_labelmenuexcursion = gtk_label_new (_("Menu excursion "));
  gtk_widget_show (Ahmed_labelmenuexcursion);
  gtk_fixed_put (GTK_FIXED (Ahmed_fixed_w_main_excur), Ahmed_labelmenuexcursion, 264, 24);
  gtk_widget_set_size_request (Ahmed_labelmenuexcursion, 136, 16);

  g_signal_connect ((gpointer) ahmed_button_modifier_main_excursion, "clicked",
                    G_CALLBACK (on_ahmed_button_modifier_main_excursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_ajouter_main_excursion, "clicked",
                    G_CALLBACK (on_ahmed_button_ajouter_main_excursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_supp_main_excursion, "clicked",
                    G_CALLBACK (on_ahmed_button_supprimer_excursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_retour_main_excursion, "clicked",
                    G_CALLBACK (on_ahmed_button_retour_main_excursion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ahmed_windowmenuexcursionprestation, ahmed_windowmenuexcursionprestation, "ahmed_windowmenuexcursionprestation");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, Ahmed_fixed_w_main_excur, "Ahmed_fixed_w_main_excur");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, ahmed_treeviewmenuexcursion, "ahmed_treeviewmenuexcursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, Ahmed_label_signa, "Ahmed_label_signa");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, ahmed_button_modifier_main_excursion, "ahmed_button_modifier_main_excursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, Ahmed_alignment22, "Ahmed_alignment22");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, image22, "image22");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, label55, "label55");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, ahmed_button_ajouter_main_excursion, "ahmed_button_ajouter_main_excursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, image21, "image21");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, label54, "label54");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, ahmed_button_supp_main_excursion, "ahmed_button_supp_main_excursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, image23, "image23");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, label56, "label56");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, ahmed_button_retour_main_excursion, "ahmed_button_retour_main_excursion");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, image24, "image24");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, label57, "label57");
  GLADE_HOOKUP_OBJECT (ahmed_windowmenuexcursionprestation, Ahmed_labelmenuexcursion, "Ahmed_labelmenuexcursion");

  return ahmed_windowmenuexcursionprestation;
}

GtkWidget*
create_ahmed_windowcataloguevoiture (void)
{
  GtkWidget *ahmed_windowcataloguevoiture;
  GtkWidget *ahmed_fixed5;
  GtkWidget *ahmed_treeview_catalogue_voiture;
  GtkWidget *ahmed_label_catalogue_voiture;
  GtkWidget *ahmed_button_retour_catalogue_voiture;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label61;
  GtkWidget *ahmed_button_supprimer_voiture_catalogue;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label63;
  GtkWidget *ahmed_button_modifier;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label62;
  GtkWidget *ahmed_button_ajouter_voiture_catalogue;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label75;
  GtkWidget *ahmed_label76;
  GtkWidget *ahmed_entryrecherchevoiturecatalogue;
  GtkWidget *ahmed_buttoncherchervoiturecatalogue;
  GtkWidget *image32;
  GtkWidget *ahmed_label78;
  GtkWidget *ahmed_button_plus_de_voiture;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image36;
  GtkWidget *label85;
  GtkWidget *image38;
  GtkWidget *image39;

  ahmed_windowcataloguevoiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ahmed_windowcataloguevoiture), _("Catalogue des voiture"));

  ahmed_fixed5 = gtk_fixed_new ();
  gtk_widget_show (ahmed_fixed5);
  gtk_container_add (GTK_CONTAINER (ahmed_windowcataloguevoiture), ahmed_fixed5);

  ahmed_treeview_catalogue_voiture = gtk_tree_view_new ();
  gtk_widget_show (ahmed_treeview_catalogue_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_treeview_catalogue_voiture, 0, 144);
  gtk_widget_set_size_request (ahmed_treeview_catalogue_voiture, 568, 272);

  ahmed_label_catalogue_voiture = gtk_label_new (_("Catalogue des voitures :"));
  gtk_widget_show (ahmed_label_catalogue_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_label_catalogue_voiture, 296, 104);
  gtk_widget_set_size_request (ahmed_label_catalogue_voiture, 192, 32);

  ahmed_button_retour_catalogue_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_retour_catalogue_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_button_retour_catalogue_voiture, 8, 32);
  gtk_widget_set_size_request (ahmed_button_retour_catalogue_voiture, 160, 40);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (ahmed_button_retour_catalogue_voiture), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox26), label61, FALSE, FALSE, 0);

  ahmed_button_supprimer_voiture_catalogue = gtk_button_new ();
  gtk_widget_show (ahmed_button_supprimer_voiture_catalogue);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_button_supprimer_voiture_catalogue, 408, 456);
  gtk_widget_set_size_request (ahmed_button_supprimer_voiture_catalogue, 120, 40);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (ahmed_button_supprimer_voiture_catalogue), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox28), label63, FALSE, FALSE, 0);

  ahmed_button_modifier = gtk_button_new ();
  gtk_widget_show (ahmed_button_modifier);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_button_modifier, 232, 456);
  gtk_widget_set_size_request (ahmed_button_modifier, 120, 40);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (ahmed_button_modifier), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox27), label62, FALSE, FALSE, 0);

  ahmed_button_ajouter_voiture_catalogue = gtk_button_new ();
  gtk_widget_show (ahmed_button_ajouter_voiture_catalogue);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_button_ajouter_voiture_catalogue, 56, 456);
  gtk_widget_set_size_request (ahmed_button_ajouter_voiture_catalogue, 120, 40);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (ahmed_button_ajouter_voiture_catalogue), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox31), label75, FALSE, FALSE, 0);

  ahmed_label76 = gtk_label_new (_("Made with <3 by Ahmed"));
  gtk_widget_show (ahmed_label76);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_label76, 736, 568);
  gtk_widget_set_size_request (ahmed_label76, 184, 32);

  ahmed_entryrecherchevoiturecatalogue = gtk_entry_new ();
  gtk_widget_show (ahmed_entryrecherchevoiturecatalogue);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_entryrecherchevoiturecatalogue, 624, 160);
  gtk_widget_set_size_request (ahmed_entryrecherchevoiturecatalogue, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ahmed_entryrecherchevoiturecatalogue), 8226);

  ahmed_buttoncherchervoiturecatalogue = gtk_button_new ();
  gtk_widget_show (ahmed_buttoncherchervoiturecatalogue);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_buttoncherchervoiturecatalogue, 824, 160);
  gtk_widget_set_size_request (ahmed_buttoncherchervoiturecatalogue, 36, 32);

  image32 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_container_add (GTK_CONTAINER (ahmed_buttoncherchervoiturecatalogue), image32);

  ahmed_label78 = gtk_label_new (_("Rechercher selon l'id :"));
  gtk_widget_show (ahmed_label78);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_label78, 616, 144);
  gtk_widget_set_size_request (ahmed_label78, 160, 16);

  ahmed_button_plus_de_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_plus_de_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), ahmed_button_plus_de_voiture, 688, 40);
  gtk_widget_set_size_request (ahmed_button_plus_de_voiture, 152, 32);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (ahmed_button_plus_de_voiture), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image36 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox34), image36, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_("Plus de voiture"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox34), label85, FALSE, FALSE, 0);

  image38 = create_pixmap (ahmed_windowcataloguevoiture, "lh_anc_car_pano_XL_fr.jpg");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), image38, 728, 272);
  gtk_widget_set_size_request (image38, 21, 21);

  image39 = create_pixmap (ahmed_windowcataloguevoiture, "ahmed_images1.jpg");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed5), image39, 592, 216);
  gtk_widget_set_size_request (image39, 288, 200);

  g_signal_connect ((gpointer) ahmed_button_retour_catalogue_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_retour_catalogue_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_supprimer_voiture_catalogue, "clicked",
                    G_CALLBACK (on_ahmed_button_supprimer_voiture_catalogue_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_modifier, "clicked",
                    G_CALLBACK (on_ahmed_button_modifier_catalogue_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_buttoncherchervoiturecatalogue, "clicked",
                    G_CALLBACK (on_ahmed_button_chercher_voiture_catalogue_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_plus_de_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_plus_de_voiture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ahmed_windowcataloguevoiture, ahmed_windowcataloguevoiture, "ahmed_windowcataloguevoiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_fixed5, "ahmed_fixed5");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_treeview_catalogue_voiture, "ahmed_treeview_catalogue_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_label_catalogue_voiture, "ahmed_label_catalogue_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_button_retour_catalogue_voiture, "ahmed_button_retour_catalogue_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, image26, "image26");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, label61, "label61");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_button_supprimer_voiture_catalogue, "ahmed_button_supprimer_voiture_catalogue");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, image28, "image28");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, label63, "label63");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_button_modifier, "ahmed_button_modifier");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, image27, "image27");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, label62, "label62");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_button_ajouter_voiture_catalogue, "ahmed_button_ajouter_voiture_catalogue");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, image31, "image31");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, label75, "label75");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_label76, "ahmed_label76");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_entryrecherchevoiturecatalogue, "ahmed_entryrecherchevoiturecatalogue");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_buttoncherchervoiturecatalogue, "ahmed_buttoncherchervoiturecatalogue");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, image32, "image32");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_label78, "ahmed_label78");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, ahmed_button_plus_de_voiture, "ahmed_button_plus_de_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, image36, "image36");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, label85, "label85");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, image38, "image38");
  GLADE_HOOKUP_OBJECT (ahmed_windowcataloguevoiture, image39, "image39");

  return ahmed_windowcataloguevoiture;
}

GtkWidget*
create_ahmed_windowmodifiervoitureprestation (void)
{
  GtkWidget *ahmed_windowmodifiervoitureprestation;
  GtkWidget *ahmed_fixed6;
  GtkWidget *Ahmed_modifierentryid;
  GtkWidget *Ahmed_entrymodifierprix;
  GtkWidget *ahmed_button_retour_modifier_voiture;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label73;
  GtkWidget *label70;
  GtkWidget *label71;
  GtkWidget *label69;
  GtkWidget *label65;
  GtkWidget *comboboxentrymodifiercarrosserie_voiture;
  GtkWidget *comboboxentrymodifiermarque_voiture;
  GtkWidget *comboboxentrymodifiermodele_voiture;
  GtkWidget *label72;
  GtkWidget *comboboxentrymodifieretat_voiture;
  GtkWidget *label68;
  GtkWidget *label67;
  GtkWidget *label66;
  GtkWidget *label64;
  GtkWidget *ahmed_entrymodifierreductionvoiture;
  GtkWidget *ahmed_button_afficher_modification_voiture;
  GtkWidget *ahmed_button_validrer_modifier_voiture;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label74;

  ahmed_windowmodifiervoitureprestation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ahmed_windowmodifiervoitureprestation), _("Modifier une voiture"));

  ahmed_fixed6 = gtk_fixed_new ();
  gtk_widget_show (ahmed_fixed6);
  gtk_container_add (GTK_CONTAINER (ahmed_windowmodifiervoitureprestation), ahmed_fixed6);

  Ahmed_modifierentryid = gtk_entry_new ();
  gtk_widget_show (Ahmed_modifierentryid);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), Ahmed_modifierentryid, 120, 120);
  gtk_widget_set_size_request (Ahmed_modifierentryid, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (Ahmed_modifierentryid), 8226);

  Ahmed_entrymodifierprix = gtk_entry_new ();
  gtk_widget_show (Ahmed_entrymodifierprix);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), Ahmed_entrymodifierprix, 576, 192);
  gtk_widget_set_size_request (Ahmed_entrymodifierprix, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (Ahmed_entrymodifierprix), 8226);

  ahmed_button_retour_modifier_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_retour_modifier_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), ahmed_button_retour_modifier_voiture, 40, 24);
  gtk_widget_set_size_request (ahmed_button_retour_modifier_voiture, 104, 32);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (ahmed_button_retour_modifier_voiture), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox29), label73, FALSE, FALSE, 0);

  label70 = gtk_label_new (_("Prix unitaire / jour :"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label70, 408, 192);
  gtk_widget_set_size_request (label70, 160, 40);

  label71 = gtk_label_new (_("R\303\251duction (en %) :"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label71, 416, 280);
  gtk_widget_set_size_request (label71, 136, 24);

  label69 = gtk_label_new (_("Etat :"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label69, 416, 120);
  gtk_widget_set_size_request (label69, 48, 24);

  label65 = gtk_label_new (_("Modifier une voiture"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label65, 304, 48);
  gtk_widget_set_size_request (label65, 168, 24);

  comboboxentrymodifiercarrosserie_voiture = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrymodifiercarrosserie_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), comboboxentrymodifiercarrosserie_voiture, 120, 352);
  gtk_widget_set_size_request (comboboxentrymodifiercarrosserie_voiture, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiercarrosserie_voiture), _("Berlin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiercarrosserie_voiture), _("Citadine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiercarrosserie_voiture), _("Pick-up"));

  comboboxentrymodifiermarque_voiture = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrymodifiermarque_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), comboboxentrymodifiermarque_voiture, 120, 192);
  gtk_widget_set_size_request (comboboxentrymodifiermarque_voiture, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiermarque_voiture), _("BMW"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiermarque_voiture), _("Skoda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiermarque_voiture), _("Toyota"));

  comboboxentrymodifiermodele_voiture = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrymodifiermodele_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), comboboxentrymodifiermodele_voiture, 120, 272);
  gtk_widget_set_size_request (comboboxentrymodifiermodele_voiture, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiermodele_voiture), _("S\303\251rie 5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiermodele_voiture), _("Fabia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifiermodele_voiture), _("LandCruiser"));

  label72 = gtk_label_new (_("Made with <3 by Ahmed"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label72, 592, 464);
  gtk_widget_set_size_request (label72, 216, 32);

  comboboxentrymodifieretat_voiture = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrymodifieretat_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), comboboxentrymodifieretat_voiture, 576, 120);
  gtk_widget_set_size_request (comboboxentrymodifieretat_voiture, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifieretat_voiture), _("Bon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymodifieretat_voiture), _("Moyen"));

  label68 = gtk_label_new (_("Carrosserie :"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label68, 8, 352);
  gtk_widget_set_size_request (label68, 96, 40);

  label67 = gtk_label_new (_("Mod\303\250le :"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label67, 8, 272);
  gtk_widget_set_size_request (label67, 72, 40);

  label66 = gtk_label_new (_("Marque  :"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label66, 0, 200);
  gtk_widget_set_size_request (label66, 96, 24);

  label64 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), label64, 8, 120);
  gtk_widget_set_size_request (label64, 88, 32);

  ahmed_entrymodifierreductionvoiture = gtk_entry_new ();
  gtk_widget_show (ahmed_entrymodifierreductionvoiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), ahmed_entrymodifierreductionvoiture, 584, 264);
  gtk_widget_set_size_request (ahmed_entrymodifierreductionvoiture, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ahmed_entrymodifierreductionvoiture), 8226);

  ahmed_button_afficher_modification_voiture = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (ahmed_button_afficher_modification_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), ahmed_button_afficher_modification_voiture, 280, 424);
  gtk_widget_set_size_request (ahmed_button_afficher_modification_voiture, 96, 32);

  ahmed_button_validrer_modifier_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_validrer_modifier_voiture);
  gtk_fixed_put (GTK_FIXED (ahmed_fixed6), ahmed_button_validrer_modifier_voiture, 448, 424);
  gtk_widget_set_size_request (ahmed_button_validrer_modifier_voiture, 96, 32);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (ahmed_button_validrer_modifier_voiture), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox30), label74, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ahmed_button_retour_modifier_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_retour_modifier_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_afficher_modification_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_afficher_modification_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_validrer_modifier_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_valider_modifier_voiture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ahmed_windowmodifiervoitureprestation, ahmed_windowmodifiervoitureprestation, "ahmed_windowmodifiervoitureprestation");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, ahmed_fixed6, "ahmed_fixed6");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, Ahmed_modifierentryid, "Ahmed_modifierentryid");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, Ahmed_entrymodifierprix, "Ahmed_entrymodifierprix");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, ahmed_button_retour_modifier_voiture, "ahmed_button_retour_modifier_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, image29, "image29");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label73, "label73");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label70, "label70");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label71, "label71");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label69, "label69");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label65, "label65");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, comboboxentrymodifiercarrosserie_voiture, "comboboxentrymodifiercarrosserie_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, comboboxentrymodifiermarque_voiture, "comboboxentrymodifiermarque_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, comboboxentrymodifiermodele_voiture, "comboboxentrymodifiermodele_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label72, "label72");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, comboboxentrymodifieretat_voiture, "comboboxentrymodifieretat_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label68, "label68");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label67, "label67");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label66, "label66");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label64, "label64");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, ahmed_entrymodifierreductionvoiture, "ahmed_entrymodifierreductionvoiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, ahmed_button_afficher_modification_voiture, "ahmed_button_afficher_modification_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, ahmed_button_validrer_modifier_voiture, "ahmed_button_validrer_modifier_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, image30, "image30");
  GLADE_HOOKUP_OBJECT (ahmed_windowmodifiervoitureprestation, label74, "label74");

  return ahmed_windowmodifiervoitureprestation;
}

GtkWidget*
create_ahmed_IDmodifiervoiture (void)
{
  GtkWidget *ahmed_IDmodifiervoiture;
  GtkWidget *fixed7;
  GtkWidget *ahmed_entryidmodifiervoiture;
  GtkWidget *ahmed_label82;
  GtkWidget *ahmed_label80;
  GtkWidget *ahmed_button_retour_modifier_ID_voiture;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image35;
  GtkWidget *label83;
  GtkWidget *ahmed_button_continuer_modifier_voiture;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image34;
  GtkWidget *label81;

  ahmed_IDmodifiervoiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ahmed_IDmodifiervoiture), _("Modifier la voiture"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (ahmed_IDmodifiervoiture), fixed7);

  ahmed_entryidmodifiervoiture = gtk_entry_new ();
  gtk_widget_show (ahmed_entryidmodifiervoiture);
  gtk_fixed_put (GTK_FIXED (fixed7), ahmed_entryidmodifiervoiture, 216, 56);
  gtk_widget_set_size_request (ahmed_entryidmodifiervoiture, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ahmed_entryidmodifiervoiture), 8226);

  ahmed_label82 = gtk_label_new (_("Made with <3 by Ahmed"));
  gtk_widget_show (ahmed_label82);
  gtk_fixed_put (GTK_FIXED (fixed7), ahmed_label82, 352, 272);
  gtk_widget_set_size_request (ahmed_label82, 200, 16);

  ahmed_label80 = gtk_label_new (_("ID de la voiture :"));
  gtk_widget_show (ahmed_label80);
  gtk_fixed_put (GTK_FIXED (fixed7), ahmed_label80, 80, 64);
  gtk_widget_set_size_request (ahmed_label80, 128, 24);

  ahmed_button_retour_modifier_ID_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_retour_modifier_ID_voiture);
  gtk_fixed_put (GTK_FIXED (fixed7), ahmed_button_retour_modifier_ID_voiture, 136, 184);
  gtk_widget_set_size_request (ahmed_button_retour_modifier_ID_voiture, 128, 32);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (ahmed_button_retour_modifier_ID_voiture), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image35 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox33), image35, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox33), label83, FALSE, FALSE, 0);

  ahmed_button_continuer_modifier_voiture = gtk_button_new ();
  gtk_widget_show (ahmed_button_continuer_modifier_voiture);
  gtk_fixed_put (GTK_FIXED (fixed7), ahmed_button_continuer_modifier_voiture, 296, 184);
  gtk_widget_set_size_request (ahmed_button_continuer_modifier_voiture, 128, 32);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (ahmed_button_continuer_modifier_voiture), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image34 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox32), image34, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox32), label81, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ahmed_button_retour_modifier_ID_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_retour_modifier_ID_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) ahmed_button_continuer_modifier_voiture, "clicked",
                    G_CALLBACK (on_ahmed_button_continuer_modifier_voiture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ahmed_IDmodifiervoiture, ahmed_IDmodifiervoiture, "ahmed_IDmodifiervoiture");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, ahmed_entryidmodifiervoiture, "ahmed_entryidmodifiervoiture");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, ahmed_label82, "ahmed_label82");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, ahmed_label80, "ahmed_label80");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, ahmed_button_retour_modifier_ID_voiture, "ahmed_button_retour_modifier_ID_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, image35, "image35");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, label83, "label83");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, ahmed_button_continuer_modifier_voiture, "ahmed_button_continuer_modifier_voiture");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, image34, "image34");
  GLADE_HOOKUP_OBJECT (ahmed_IDmodifiervoiture, label81, "label81");

  return ahmed_IDmodifiervoiture;
}

