/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ahmed_windowajoutervoitureprestation (void);
GtkWidget* create_ahmed_windowajoutexcursionprestation (void);
GtkWidget* create_ahmed_windowmenuvoitureprestation (void);
GtkWidget* create_ahmed_windowmenuexcursionprestation (void);
GtkWidget* create_ahmed_windowcataloguevoiture (void);
GtkWidget* create_ahmed_windowmodifiervoitureprestation (void);
GtkWidget* create_ahmed_IDmodifiervoiture (void);
