/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ahmed_windowajoutervoitureprestation;
  //GtkWidget *ahmed_windowajoutexcursionprestation;
  GtkWidget *ahmed_windowmenuvoitureprestation;
  //GtkWidget *ahmed_windowmenuexcursionprestation;
  GtkWidget *ahmed_windowcataloguevoiture;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
//  ahmed_windowajoutervoitureprestation = create_ahmed_windowajoutervoitureprestation ();
//  gtk_widget_show (ahmed_windowajoutervoitureprestation);
 // ahmed_windowajoutexcursionprestation = create_ahmed_windowajoutexcursionprestation ();
//  gtk_widget_show (ahmed_windowajoutexcursionprestation);
//  ahmed_windowmenuvoitureprestation = create_ahmed_windowmenuvoitureprestation ();
//  gtk_widget_show (ahmed_windowmenuvoitureprestation);
//  ahmed_windowmenuexcursionprestation = create_ahmed_windowmenuexcursionprestation ();
//  gtk_widget_show (ahmed_windowmenuexcursionprestation);
  ahmed_windowcataloguevoiture = create_ahmed_windowcataloguevoiture();
  gtk_widget_show (ahmed_windowcataloguevoiture);

  gtk_main ();
  return 0;
}

