/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_YassRecEspaceAAWind (void);
GtkWidget* create_YassRepondreRecWind (void);
GtkWidget* create_YassRecEspaceCWind (void);
GtkWidget* create_YassSkytravelMainWind (void);
GtkWidget* create_YassCatWind (void);
GtkWidget* create_YassInscriWind (void);
GtkWidget* create_YasswindowGestion (void);
GtkWidget* create_YassAfficherVosRecWind (void);
GtkWidget* create_YassEspaceAdminWind (void);
GtkWidget* create_YassEspaceAgentWind (void);
GtkWidget* create_YassReserverVoiture (void);
