/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_YassRecEspaceAAWind (void)
{
  GtkWidget *YassRecEspaceAAWind;
  GtkWidget *fixed_rec;
  GtkWidget *YasstreeviewRec;
  GtkWidget *yass_entry_repondre_reclamationAA;
  GtkWidget *YasslabelRec;
  GtkWidget *YassbuttonSuppRec;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *YassimgBotnSuppRec;
  GtkWidget *YasslabelBotnSuppRec;
  GtkWidget *yasslabel_repondre;
  GtkWidget *YassbuttonRepondreRec;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *YassimgbotnRepondreRec;
  GtkWidget *YasslabelBotnRepondreRec;

  YassRecEspaceAAWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassRecEspaceAAWind), _("YassRecEspaceAA"));

  fixed_rec = gtk_fixed_new ();
  gtk_widget_show (fixed_rec);
  gtk_container_add (GTK_CONTAINER (YassRecEspaceAAWind), fixed_rec);

  YasstreeviewRec = gtk_tree_view_new ();
  gtk_widget_show (YasstreeviewRec);
  gtk_fixed_put (GTK_FIXED (fixed_rec), YasstreeviewRec, 0, 40);
  gtk_widget_set_size_request (YasstreeviewRec, 1088, 248);

  yass_entry_repondre_reclamationAA = gtk_entry_new ();
  gtk_widget_show (yass_entry_repondre_reclamationAA);
  gtk_fixed_put (GTK_FIXED (fixed_rec), yass_entry_repondre_reclamationAA, 632, 296);
  gtk_widget_set_size_request (yass_entry_repondre_reclamationAA, 296, 80);
  gtk_entry_set_invisible_char (GTK_ENTRY (yass_entry_repondre_reclamationAA), 8226);

  YasslabelRec = gtk_label_new (_("Les R\303\251clamations"));
  gtk_widget_show (YasslabelRec);
  gtk_fixed_put (GTK_FIXED (fixed_rec), YasslabelRec, 8, 8);
  gtk_widget_set_size_request (YasslabelRec, 160, 32);

  YassbuttonSuppRec = gtk_button_new ();
  gtk_widget_show (YassbuttonSuppRec);
  gtk_fixed_put (GTK_FIXED (fixed_rec), YassbuttonSuppRec, 896, 392);
  gtk_widget_set_size_request (YassbuttonSuppRec, 96, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (YassbuttonSuppRec), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  YassimgBotnSuppRec = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (YassimgBotnSuppRec);
  gtk_box_pack_start (GTK_BOX (hbox2), YassimgBotnSuppRec, FALSE, FALSE, 0);

  YasslabelBotnSuppRec = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (YasslabelBotnSuppRec);
  gtk_box_pack_start (GTK_BOX (hbox2), YasslabelBotnSuppRec, FALSE, FALSE, 0);

  yasslabel_repondre = gtk_label_new (_("R\303\251pondre"));
  gtk_widget_show (yasslabel_repondre);
  gtk_fixed_put (GTK_FIXED (fixed_rec), yasslabel_repondre, 496, 304);
  gtk_widget_set_size_request (yasslabel_repondre, 136, 64);

  YassbuttonRepondreRec = gtk_button_new ();
  gtk_widget_show (YassbuttonRepondreRec);
  gtk_fixed_put (GTK_FIXED (fixed_rec), YassbuttonRepondreRec, 784, 392);
  gtk_widget_set_size_request (YassbuttonRepondreRec, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (YassbuttonRepondreRec), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  YassimgbotnRepondreRec = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (YassimgbotnRepondreRec);
  gtk_box_pack_start (GTK_BOX (hbox3), YassimgbotnRepondreRec, FALSE, FALSE, 0);

  YasslabelBotnRepondreRec = gtk_label_new_with_mnemonic (_("Repondre"));
  gtk_widget_show (YasslabelBotnRepondreRec);
  gtk_box_pack_start (GTK_BOX (hbox3), YasslabelBotnRepondreRec, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) YasstreeviewRec, "columns_changed",
                    G_CALLBACK (on_YasstreeviewRec_columns_changed),
                    NULL);
  g_signal_connect ((gpointer) YassbuttonSuppRec, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) YassbuttonRepondreRec, "clicked",
                    G_CALLBACK (on_YassbuttonRepondreRec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassRecEspaceAAWind, YassRecEspaceAAWind, "YassRecEspaceAAWind");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, fixed_rec, "fixed_rec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, YasstreeviewRec, "YasstreeviewRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, yass_entry_repondre_reclamationAA, "yass_entry_repondre_reclamationAA");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, YasslabelRec, "YasslabelRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, YassbuttonSuppRec, "YassbuttonSuppRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, YassimgBotnSuppRec, "YassimgBotnSuppRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, YasslabelBotnSuppRec, "YasslabelBotnSuppRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, yasslabel_repondre, "yasslabel_repondre");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, YassbuttonRepondreRec, "YassbuttonRepondreRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, YassimgbotnRepondreRec, "YassimgbotnRepondreRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceAAWind, YasslabelBotnRepondreRec, "YasslabelBotnRepondreRec");

  return YassRecEspaceAAWind;
}

GtkWidget*
create_YassRepondreRecWind (void)
{
  GtkWidget *YassRepondreRecWind;
  GtkWidget *fixed_repondreAA;
  GtkWidget *YassentrySaisieReponseAA;
  GtkWidget *Y_buttonRetour_fromRepRec;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *Yassimgbutton_retour_from_CRec;
  GtkWidget *Yasslabel_button_retour_from_CRec;
  GtkWidget *YasslabelSaisieRepAA;
  GtkWidget *YasslabelRepRec;
  GtkWidget *YassbuttonRepRecAA;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *YassimgBotnTerminerRepRecAA;
  GtkWidget *YasslabelBotnTerminerRepRecAA;

  YassRepondreRecWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassRepondreRecWind), _("repondre_rec"));

  fixed_repondreAA = gtk_fixed_new ();
  gtk_widget_show (fixed_repondreAA);
  gtk_container_add (GTK_CONTAINER (YassRepondreRecWind), fixed_repondreAA);

  YassentrySaisieReponseAA = gtk_entry_new ();
  gtk_widget_show (YassentrySaisieReponseAA);
  gtk_fixed_put (GTK_FIXED (fixed_repondreAA), YassentrySaisieReponseAA, 72, 96);
  gtk_widget_set_size_request (YassentrySaisieReponseAA, 304, 120);
  gtk_entry_set_invisible_char (GTK_ENTRY (YassentrySaisieReponseAA), 8226);

  Y_buttonRetour_fromRepRec = gtk_button_new ();
  gtk_widget_show (Y_buttonRetour_fromRepRec);
  gtk_fixed_put (GTK_FIXED (fixed_repondreAA), Y_buttonRetour_fromRepRec, 480, 384);
  gtk_widget_set_size_request (Y_buttonRetour_fromRepRec, 90, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (Y_buttonRetour_fromRepRec), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  Yassimgbutton_retour_from_CRec = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (Yassimgbutton_retour_from_CRec);
  gtk_box_pack_start (GTK_BOX (hbox10), Yassimgbutton_retour_from_CRec, FALSE, FALSE, 0);

  Yasslabel_button_retour_from_CRec = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (Yasslabel_button_retour_from_CRec);
  gtk_box_pack_start (GTK_BOX (hbox10), Yasslabel_button_retour_from_CRec, FALSE, FALSE, 0);

  YasslabelSaisieRepAA = gtk_label_new (_("saisir le reponse"));
  gtk_widget_show (YasslabelSaisieRepAA);
  gtk_fixed_put (GTK_FIXED (fixed_repondreAA), YasslabelSaisieRepAA, 72, 72);
  gtk_widget_set_size_request (YasslabelSaisieRepAA, 192, 16);

  YasslabelRepRec = gtk_label_new (_("R\303\251pondre"));
  gtk_widget_show (YasslabelRepRec);
  gtk_fixed_put (GTK_FIXED (fixed_repondreAA), YasslabelRepRec, 32, 16);
  gtk_widget_set_size_request (YasslabelRepRec, 536, 32);

  YassbuttonRepRecAA = gtk_button_new ();
  gtk_widget_show (YassbuttonRepRecAA);
  gtk_fixed_put (GTK_FIXED (fixed_repondreAA), YassbuttonRepRecAA, 136, 248);
  gtk_widget_set_size_request (YassbuttonRepRecAA, 104, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (YassbuttonRepRecAA), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  YassimgBotnTerminerRepRecAA = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (YassimgBotnTerminerRepRecAA);
  gtk_box_pack_start (GTK_BOX (hbox1), YassimgBotnTerminerRepRecAA, FALSE, FALSE, 0);

  YasslabelBotnTerminerRepRecAA = gtk_label_new_with_mnemonic (_("Terminer"));
  gtk_widget_show (YasslabelBotnTerminerRepRecAA);
  gtk_box_pack_start (GTK_BOX (hbox1), YasslabelBotnTerminerRepRecAA, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Y_buttonRetour_fromRepRec, "clicked",
                    G_CALLBACK (on_Y_buttonRetour_fromRepRec_clicked),
                    NULL);
  g_signal_connect ((gpointer) YassbuttonRepRecAA, "clicked",
                    G_CALLBACK (on_YassbuttonRepRecAA_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassRepondreRecWind, YassRepondreRecWind, "YassRepondreRecWind");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, fixed_repondreAA, "fixed_repondreAA");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, YassentrySaisieReponseAA, "YassentrySaisieReponseAA");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, Y_buttonRetour_fromRepRec, "Y_buttonRetour_fromRepRec");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, Yassimgbutton_retour_from_CRec, "Yassimgbutton_retour_from_CRec");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, Yasslabel_button_retour_from_CRec, "Yasslabel_button_retour_from_CRec");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, YasslabelSaisieRepAA, "YasslabelSaisieRepAA");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, YasslabelRepRec, "YasslabelRepRec");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, YassbuttonRepRecAA, "YassbuttonRepRecAA");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, YassimgBotnTerminerRepRecAA, "YassimgBotnTerminerRepRecAA");
  GLADE_HOOKUP_OBJECT (YassRepondreRecWind, YasslabelBotnTerminerRepRecAA, "YasslabelBotnTerminerRepRecAA");

  return YassRepondreRecWind;
}

GtkWidget*
create_YassRecEspaceCWind (void)
{
  GtkWidget *YassRecEspaceCWind;
  GtkWidget *YassfixedRecClient;
  GtkWidget *YassentryClientAjoutRec;
  GtkWidget *YasslabelClientRec;
  GtkWidget *Y_label_typeRec;
  GtkWidget *YasslabelClientAjoutRec;
  GtkWidget *label46;
  GtkWidget *Y_button_retour_from_CRec;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image7;
  GtkWidget *Y_labelBotn_Retou_RecEspClient;
  GtkWidget *Y_button_quit_fromCRrec;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image8;
  GtkWidget *Y_labelBotn_Quitter_RecEspClient;
  GtkObject *Yassspinbutton_date_fin_service_jour_adj;
  GtkWidget *Yassspinbutton_date_fin_service_jour;
  GtkObject *Yassspinbutton_date_fin_service_mois_adj;
  GtkWidget *Yassspinbutton_date_fin_service_mois;
  GtkObject *Yassspinbutton_date_fin_service_annee_adj;
  GtkWidget *Yassspinbutton_date_fin_service_annee;
  GtkWidget *yass_button_affichRecClient;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image11;
  GtkWidget *Y_labelBotn_Afficher_RecEspClient;
  GtkWidget *Yasslabel_datefinservice;
  GtkWidget *YassbuttonClientEnvoyerRec;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image12;
  GtkWidget *Y_labelBotn_Envoyer_RecEspClient;
  GtkWidget *Yass_label_outputAjouterRec;
  GtkWidget *Y_combobox_ServiceReclamee;
  GtkWidget *Y_combobox_type_rec;

  YassRecEspaceCWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassRecEspaceCWind), _("Yass Ajouter RecEspaceC"));

  YassfixedRecClient = gtk_fixed_new ();
  gtk_widget_show (YassfixedRecClient);
  gtk_container_add (GTK_CONTAINER (YassRecEspaceCWind), YassfixedRecClient);

  YassentryClientAjoutRec = gtk_entry_new ();
  gtk_widget_show (YassentryClientAjoutRec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), YassentryClientAjoutRec, 48, 280);
  gtk_widget_set_size_request (YassentryClientAjoutRec, 312, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (YassentryClientAjoutRec), 8226);

  YasslabelClientRec = gtk_label_new (_("Reclamations"));
  gtk_widget_show (YasslabelClientRec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), YasslabelClientRec, 320, 8);
  gtk_widget_set_size_request (YasslabelClientRec, 128, 32);

  Y_label_typeRec = gtk_label_new (_("Type de Reclamation "));
  gtk_widget_show (Y_label_typeRec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Y_label_typeRec, 40, 192);
  gtk_widget_set_size_request (Y_label_typeRec, 168, 24);

  YasslabelClientAjoutRec = gtk_label_new (_("Ajouter votre  reclamation :"));
  gtk_widget_show (YasslabelClientAjoutRec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), YasslabelClientAjoutRec, 40, 240);
  gtk_widget_set_size_request (YasslabelClientAjoutRec, 216, 40);

  label46 = gtk_label_new (_("Service a reclamer"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), label46, 16, 128);
  gtk_widget_set_size_request (label46, 200, 32);

  Y_button_retour_from_CRec = gtk_button_new ();
  gtk_widget_show (Y_button_retour_from_CRec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Y_button_retour_from_CRec, 520, 496);
  gtk_widget_set_size_request (Y_button_retour_from_CRec, 82, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (Y_button_retour_from_CRec), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox8), image7, FALSE, FALSE, 0);

  Y_labelBotn_Retou_RecEspClient = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (Y_labelBotn_Retou_RecEspClient);
  gtk_box_pack_start (GTK_BOX (hbox8), Y_labelBotn_Retou_RecEspClient, FALSE, FALSE, 0);

  Y_button_quit_fromCRrec = gtk_button_new ();
  gtk_widget_show (Y_button_quit_fromCRrec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Y_button_quit_fromCRrec, 608, 496);
  gtk_widget_set_size_request (Y_button_quit_fromCRrec, 98, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (Y_button_quit_fromCRrec), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox9), image8, FALSE, FALSE, 0);

  Y_labelBotn_Quitter_RecEspClient = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (Y_labelBotn_Quitter_RecEspClient);
  gtk_box_pack_start (GTK_BOX (hbox9), Y_labelBotn_Quitter_RecEspClient, FALSE, FALSE, 0);

  Yassspinbutton_date_fin_service_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  Yassspinbutton_date_fin_service_jour = gtk_spin_button_new (GTK_ADJUSTMENT (Yassspinbutton_date_fin_service_jour_adj), 1, 0);
  gtk_widget_show (Yassspinbutton_date_fin_service_jour);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Yassspinbutton_date_fin_service_jour, 616, 208);
  gtk_widget_set_size_request (Yassspinbutton_date_fin_service_jour, 60, 27);

  Yassspinbutton_date_fin_service_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  Yassspinbutton_date_fin_service_mois = gtk_spin_button_new (GTK_ADJUSTMENT (Yassspinbutton_date_fin_service_mois_adj), 1, 0);
  gtk_widget_show (Yassspinbutton_date_fin_service_mois);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Yassspinbutton_date_fin_service_mois, 696, 208);
  gtk_widget_set_size_request (Yassspinbutton_date_fin_service_mois, 60, 27);

  Yassspinbutton_date_fin_service_annee_adj = gtk_adjustment_new (1, 2019, 2023, 1, 10, 10);
  Yassspinbutton_date_fin_service_annee = gtk_spin_button_new (GTK_ADJUSTMENT (Yassspinbutton_date_fin_service_annee_adj), 1, 0);
  gtk_widget_show (Yassspinbutton_date_fin_service_annee);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Yassspinbutton_date_fin_service_annee, 768, 208);
  gtk_widget_set_size_request (Yassspinbutton_date_fin_service_annee, 60, 27);

  yass_button_affichRecClient = gtk_button_new ();
  gtk_widget_show (yass_button_affichRecClient);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), yass_button_affichRecClient, 376, 368);
  gtk_widget_set_size_request (yass_button_affichRecClient, 106, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (yass_button_affichRecClient), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image11 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox13), image11, FALSE, FALSE, 0);

  Y_labelBotn_Afficher_RecEspClient = gtk_label_new_with_mnemonic (_("Afficher "));
  gtk_widget_show (Y_labelBotn_Afficher_RecEspClient);
  gtk_box_pack_start (GTK_BOX (hbox13), Y_labelBotn_Afficher_RecEspClient, FALSE, FALSE, 0);

  Yasslabel_datefinservice = gtk_label_new (_("Date fin de service :"));
  gtk_widget_show (Yasslabel_datefinservice);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Yasslabel_datefinservice, 568, 144);
  gtk_widget_set_size_request (Yasslabel_datefinservice, 280, 40);

  YassbuttonClientEnvoyerRec = gtk_button_new ();
  gtk_widget_show (YassbuttonClientEnvoyerRec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), YassbuttonClientEnvoyerRec, 232, 368);
  gtk_widget_set_size_request (YassbuttonClientEnvoyerRec, 96, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (YassbuttonClientEnvoyerRec), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image12 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox14), image12, FALSE, FALSE, 0);

  Y_labelBotn_Envoyer_RecEspClient = gtk_label_new_with_mnemonic (_("Envoyer"));
  gtk_widget_show (Y_labelBotn_Envoyer_RecEspClient);
  gtk_box_pack_start (GTK_BOX (hbox14), Y_labelBotn_Envoyer_RecEspClient, FALSE, FALSE, 0);

  Yass_label_outputAjouterRec = gtk_label_new ("");
  gtk_widget_show (Yass_label_outputAjouterRec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Yass_label_outputAjouterRec, 64, 408);
  gtk_widget_set_size_request (Yass_label_outputAjouterRec, 720, 72);

  Y_combobox_ServiceReclamee = gtk_combo_box_new_text ();
  gtk_widget_show (Y_combobox_ServiceReclamee);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Y_combobox_ServiceReclamee, 240, 128);
  gtk_widget_set_size_request (Y_combobox_ServiceReclamee, 232, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_ServiceReclamee), _("Hotels"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_ServiceReclamee), _("Vols"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_ServiceReclamee), _("Voitures"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_ServiceReclamee), _("Excursions"));

  Y_combobox_type_rec = gtk_combo_box_new_text ();
  gtk_widget_show (Y_combobox_type_rec);
  gtk_fixed_put (GTK_FIXED (YassfixedRecClient), Y_combobox_type_rec, 240, 184);
  gtk_widget_set_size_request (Y_combobox_type_rec, 232, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_type_rec), _("Services"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_type_rec), _("Prix"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_type_rec), _("Confort"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_type_rec), _("Retard"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Y_combobox_type_rec), _("autres"));

  g_signal_connect ((gpointer) Y_button_retour_from_CRec, "clicked",
                    G_CALLBACK (on_Y_button_retour_from_CRec_clicked),
                    NULL);
  g_signal_connect ((gpointer) Y_button_quit_fromCRrec, "clicked",
                    G_CALLBACK (on_Y_button_quit_fromCRrec_clicked),
                    NULL);
  g_signal_connect ((gpointer) yass_button_affichRecClient, "clicked",
                    G_CALLBACK (on_yass_button_affichRecClient_clicked),
                    NULL);
  g_signal_connect ((gpointer) YassbuttonClientEnvoyerRec, "clicked",
                    G_CALLBACK (on_YassbuttonClientEnvoyerRec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassRecEspaceCWind, YassRecEspaceCWind, "YassRecEspaceCWind");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, YassfixedRecClient, "YassfixedRecClient");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, YassentryClientAjoutRec, "YassentryClientAjoutRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, YasslabelClientRec, "YasslabelClientRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_label_typeRec, "Y_label_typeRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, YasslabelClientAjoutRec, "YasslabelClientAjoutRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, label46, "label46");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_button_retour_from_CRec, "Y_button_retour_from_CRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, image7, "image7");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_labelBotn_Retou_RecEspClient, "Y_labelBotn_Retou_RecEspClient");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_button_quit_fromCRrec, "Y_button_quit_fromCRrec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, image8, "image8");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_labelBotn_Quitter_RecEspClient, "Y_labelBotn_Quitter_RecEspClient");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Yassspinbutton_date_fin_service_jour, "Yassspinbutton_date_fin_service_jour");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Yassspinbutton_date_fin_service_mois, "Yassspinbutton_date_fin_service_mois");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Yassspinbutton_date_fin_service_annee, "Yassspinbutton_date_fin_service_annee");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, yass_button_affichRecClient, "yass_button_affichRecClient");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, image11, "image11");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_labelBotn_Afficher_RecEspClient, "Y_labelBotn_Afficher_RecEspClient");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Yasslabel_datefinservice, "Yasslabel_datefinservice");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, YassbuttonClientEnvoyerRec, "YassbuttonClientEnvoyerRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, image12, "image12");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_labelBotn_Envoyer_RecEspClient, "Y_labelBotn_Envoyer_RecEspClient");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Yass_label_outputAjouterRec, "Yass_label_outputAjouterRec");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_combobox_ServiceReclamee, "Y_combobox_ServiceReclamee");
  GLADE_HOOKUP_OBJECT (YassRecEspaceCWind, Y_combobox_type_rec, "Y_combobox_type_rec");

  return YassRecEspaceCWind;
}

GtkWidget*
create_YassSkytravelMainWind (void)
{
  GtkWidget *YassSkytravelMainWind;
  GtkWidget *YassfixedBienvenue;
  GtkWidget *YassentryMdp;
  GtkWidget *YassentryLogin;
  GtkWidget *label_Author_Yass;
  GtkWidget *YasslabelLogin;
  GtkWidget *YasslabelMdp;
  GtkWidget *YassbuttonInscri;
  GtkWidget *Yass_buttonQuit_fromMainW;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *YassimgBotnQuit;
  GtkWidget *YasslabelBotnQuit;
  GtkWidget *YasslabelBienvenue;
  GtkWidget *Yass_label_main_page_error;
  GtkWidget *YassbuttonLogin;
  GtkWidget *YassbuttonCatNA;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *YassimgBotnCat;
  GtkWidget *YasslabelBotnCat;
  GtkWidget *YassImgIcon;

  YassSkytravelMainWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassSkytravelMainWind), _("Bienvenue dans notre agence skytravel"));

  YassfixedBienvenue = gtk_fixed_new ();
  gtk_widget_show (YassfixedBienvenue);
  gtk_container_add (GTK_CONTAINER (YassSkytravelMainWind), YassfixedBienvenue);

  YassentryMdp = gtk_entry_new ();
  gtk_widget_show (YassentryMdp);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YassentryMdp, 552, 152);
  gtk_widget_set_size_request (YassentryMdp, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (YassentryMdp), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (YassentryMdp), 8226);

  YassentryLogin = gtk_entry_new ();
  gtk_widget_show (YassentryLogin);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YassentryLogin, 552, 104);
  gtk_widget_set_size_request (YassentryLogin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (YassentryLogin), 8226);

  label_Author_Yass = gtk_label_new (_("Made with <3 by Yassine"));
  gtk_widget_show (label_Author_Yass);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), label_Author_Yass, 0, 360);
  gtk_widget_set_size_request (label_Author_Yass, 176, 32);

  YasslabelLogin = gtk_label_new (_("Login"));
  gtk_widget_show (YasslabelLogin);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YasslabelLogin, 480, 104);
  gtk_widget_set_size_request (YasslabelLogin, 49, 17);

  YasslabelMdp = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (YasslabelMdp);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YasslabelMdp, 424, 160);
  gtk_widget_set_size_request (YasslabelMdp, 105, 16);

  YassbuttonInscri = gtk_button_new_with_mnemonic (_("s'incrire"));
  gtk_widget_show (YassbuttonInscri);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YassbuttonInscri, 496, 264);
  gtk_widget_set_size_request (YassbuttonInscri, 104, 32);

  Yass_buttonQuit_fromMainW = gtk_button_new ();
  gtk_widget_show (Yass_buttonQuit_fromMainW);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), Yass_buttonQuit_fromMainW, 672, 360);
  gtk_widget_set_size_request (Yass_buttonQuit_fromMainW, 104, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (Yass_buttonQuit_fromMainW), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  YassimgBotnQuit = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (YassimgBotnQuit);
  gtk_box_pack_start (GTK_BOX (hbox6), YassimgBotnQuit, FALSE, FALSE, 0);

  YasslabelBotnQuit = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (YasslabelBotnQuit);
  gtk_box_pack_start (GTK_BOX (hbox6), YasslabelBotnQuit, FALSE, FALSE, 0);

  YasslabelBienvenue = gtk_label_new (_("Bienvenue dans notre agence Sky Travel "));
  gtk_widget_show (YasslabelBienvenue);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YasslabelBienvenue, 312, 8);
  gtk_widget_set_size_request (YasslabelBienvenue, 448, 56);

  Yass_label_main_page_error = gtk_label_new ("");
  gtk_widget_show (Yass_label_main_page_error);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), Yass_label_main_page_error, 424, 184);
  gtk_widget_set_size_request (Yass_label_main_page_error, 336, 41);

  YassbuttonLogin = gtk_button_new_with_mnemonic (_("s'identifier"));
  gtk_widget_show (YassbuttonLogin);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YassbuttonLogin, 496, 224);
  gtk_widget_set_size_request (YassbuttonLogin, 104, 32);

  YassbuttonCatNA = gtk_button_new ();
  gtk_widget_show (YassbuttonCatNA);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YassbuttonCatNA, 40, 288);
  gtk_widget_set_size_request (YassbuttonCatNA, 232, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (YassbuttonCatNA), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  YassimgBotnCat = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (YassimgBotnCat);
  gtk_box_pack_start (GTK_BOX (hbox5), YassimgBotnCat, FALSE, FALSE, 0);

  YasslabelBotnCat = gtk_label_new_with_mnemonic (_("Catalogue"));
  gtk_widget_show (YasslabelBotnCat);
  gtk_box_pack_start (GTK_BOX (hbox5), YasslabelBotnCat, FALSE, FALSE, 0);

  YassImgIcon = create_pixmap (YassSkytravelMainWind, "sky_travel1..jpg");
  gtk_widget_show (YassImgIcon);
  gtk_fixed_put (GTK_FIXED (YassfixedBienvenue), YassImgIcon, 0, 0);
  gtk_widget_set_size_request (YassImgIcon, 312, 280);

  g_signal_connect ((gpointer) YassbuttonInscri, "clicked",
                    G_CALLBACK (on_YassbuttonInscri_clicked),
                    NULL);
  g_signal_connect ((gpointer) Yass_buttonQuit_fromMainW, "clicked",
                    G_CALLBACK (on_Yass_buttonQuit_fromMainW_clicked),
                    NULL);
  g_signal_connect ((gpointer) YassbuttonLogin, "clicked",
                    G_CALLBACK (on_YassbuttonLogin_clicked),
                    NULL);
  g_signal_connect ((gpointer) YassbuttonCatNA, "clicked",
                    G_CALLBACK (on_YassbuttonCatNA_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassSkytravelMainWind, YassSkytravelMainWind, "YassSkytravelMainWind");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassfixedBienvenue, "YassfixedBienvenue");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassentryMdp, "YassentryMdp");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassentryLogin, "YassentryLogin");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, label_Author_Yass, "label_Author_Yass");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YasslabelLogin, "YasslabelLogin");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YasslabelMdp, "YasslabelMdp");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassbuttonInscri, "YassbuttonInscri");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, Yass_buttonQuit_fromMainW, "Yass_buttonQuit_fromMainW");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassimgBotnQuit, "YassimgBotnQuit");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YasslabelBotnQuit, "YasslabelBotnQuit");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YasslabelBienvenue, "YasslabelBienvenue");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, Yass_label_main_page_error, "Yass_label_main_page_error");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassbuttonLogin, "YassbuttonLogin");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassbuttonCatNA, "YassbuttonCatNA");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassimgBotnCat, "YassimgBotnCat");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YasslabelBotnCat, "YasslabelBotnCat");
  GLADE_HOOKUP_OBJECT (YassSkytravelMainWind, YassImgIcon, "YassImgIcon");

  return YassSkytravelMainWind;
}

GtkWidget*
create_YassCatWind (void)
{
  GtkWidget *YassCatWind;
  GtkWidget *notebook1;
  GtkWidget *YassfixedCatHtl;
  GtkWidget *YasstreeviewCatHtl;
  GtkWidget *YasslabelCatHtl;
  GtkWidget *YassfixedCatvols;
  GtkWidget *YasstreeviewCatVols;
  GtkWidget *YasslabelCatVl;
  GtkWidget *YassfixedCatVoit;
  GtkWidget *YasstreeviewCatVoit;
  GtkWidget *YasslabelCatVoit;
  GtkWidget *YassfixedCatEx;
  GtkWidget *YasstreeviewCatEx;
  GtkWidget *YasslabelCatEx;

  YassCatWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassCatWind), _("Catalogue"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (YassCatWind), notebook1);

  YassfixedCatHtl = gtk_fixed_new ();
  gtk_widget_show (YassfixedCatHtl);
  gtk_container_add (GTK_CONTAINER (notebook1), YassfixedCatHtl);

  YasstreeviewCatHtl = gtk_tree_view_new ();
  gtk_widget_show (YasstreeviewCatHtl);
  gtk_fixed_put (GTK_FIXED (YassfixedCatHtl), YasstreeviewCatHtl, 120, 72);
  gtk_widget_set_size_request (YasstreeviewCatHtl, 300, 200);

  YasslabelCatHtl = gtk_label_new (_("Hotels"));
  gtk_widget_show (YasslabelCatHtl);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), YasslabelCatHtl);

  YassfixedCatvols = gtk_fixed_new ();
  gtk_widget_show (YassfixedCatvols);
  gtk_container_add (GTK_CONTAINER (notebook1), YassfixedCatvols);

  YasstreeviewCatVols = gtk_tree_view_new ();
  gtk_widget_show (YasstreeviewCatVols);
  gtk_fixed_put (GTK_FIXED (YassfixedCatvols), YasstreeviewCatVols, 120, 72);
  gtk_widget_set_size_request (YasstreeviewCatVols, 300, 200);

  YasslabelCatVl = gtk_label_new (_("vols"));
  gtk_widget_show (YasslabelCatVl);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), YasslabelCatVl);

  YassfixedCatVoit = gtk_fixed_new ();
  gtk_widget_show (YassfixedCatVoit);
  gtk_container_add (GTK_CONTAINER (notebook1), YassfixedCatVoit);

  YasstreeviewCatVoit = gtk_tree_view_new ();
  gtk_widget_show (YasstreeviewCatVoit);
  gtk_fixed_put (GTK_FIXED (YassfixedCatVoit), YasstreeviewCatVoit, 120, 72);
  gtk_widget_set_size_request (YasstreeviewCatVoit, 300, 200);

  YasslabelCatVoit = gtk_label_new (_("Voitures"));
  gtk_widget_show (YasslabelCatVoit);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), YasslabelCatVoit);

  YassfixedCatEx = gtk_fixed_new ();
  gtk_widget_show (YassfixedCatEx);
  gtk_container_add (GTK_CONTAINER (notebook1), YassfixedCatEx);

  YasstreeviewCatEx = gtk_tree_view_new ();
  gtk_widget_show (YasstreeviewCatEx);
  gtk_fixed_put (GTK_FIXED (YassfixedCatEx), YasstreeviewCatEx, 120, 72);
  gtk_widget_set_size_request (YasstreeviewCatEx, 392, 288);

  YasslabelCatEx = gtk_label_new (_("Excursions"));
  gtk_widget_show (YasslabelCatEx);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), YasslabelCatEx);

  g_signal_connect ((gpointer) YasstreeviewCatHtl, "columns_changed",
                    G_CALLBACK (on_YasstreeviewCatHtl_columns_changed),
                    NULL);
  g_signal_connect ((gpointer) YasstreeviewCatVols, "columns_changed",
                    G_CALLBACK (on_YasstreeviewCatVols_columns_changed),
                    NULL);
  g_signal_connect ((gpointer) YasstreeviewCatVoit, "columns_changed",
                    G_CALLBACK (on_YasstreeviewCatVoit_columns_changed),
                    NULL);
  g_signal_connect ((gpointer) YasstreeviewCatEx, "columns_changed",
                    G_CALLBACK (on_YasstreeviewCatEx_columns_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassCatWind, YassCatWind, "YassCatWind");
  GLADE_HOOKUP_OBJECT (YassCatWind, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (YassCatWind, YassfixedCatHtl, "YassfixedCatHtl");
  GLADE_HOOKUP_OBJECT (YassCatWind, YasstreeviewCatHtl, "YasstreeviewCatHtl");
  GLADE_HOOKUP_OBJECT (YassCatWind, YasslabelCatHtl, "YasslabelCatHtl");
  GLADE_HOOKUP_OBJECT (YassCatWind, YassfixedCatvols, "YassfixedCatvols");
  GLADE_HOOKUP_OBJECT (YassCatWind, YasstreeviewCatVols, "YasstreeviewCatVols");
  GLADE_HOOKUP_OBJECT (YassCatWind, YasslabelCatVl, "YasslabelCatVl");
  GLADE_HOOKUP_OBJECT (YassCatWind, YassfixedCatVoit, "YassfixedCatVoit");
  GLADE_HOOKUP_OBJECT (YassCatWind, YasstreeviewCatVoit, "YasstreeviewCatVoit");
  GLADE_HOOKUP_OBJECT (YassCatWind, YasslabelCatVoit, "YasslabelCatVoit");
  GLADE_HOOKUP_OBJECT (YassCatWind, YassfixedCatEx, "YassfixedCatEx");
  GLADE_HOOKUP_OBJECT (YassCatWind, YasstreeviewCatEx, "YasstreeviewCatEx");
  GLADE_HOOKUP_OBJECT (YassCatWind, YasslabelCatEx, "YasslabelCatEx");

  return YassCatWind;
}

GtkWidget*
create_YassInscriWind (void)
{
  GtkWidget *YassInscriWind;
  GtkWidget *YassfixedInscri;
  GtkWidget *Y_entry_insc_nom;
  GtkWidget *Y_entry_insc_prenom;
  GtkWidget *Y_entry_insc_login;
  GtkWidget *Y_entry_insc_pwd;
  GtkWidget *Y_entry_insc_;
  GtkObject *Y_spinbutton_Idnj_adj;
  GtkWidget *Y_spinbutton_Idnj;
  GtkObject *Y_spinbutton_idnm_adj;
  GtkWidget *Y_spinbutton_idnm;
  GtkObject *Y_spinbutton_idna_adj;
  GtkWidget *Y_spinbutton_idna;
  GtkWidget *YassLabel_inscriDN;
  GtkWidget *YassLabel_inscrilogin;
  GtkWidget *Y_entry_insc_cin;
  GtkWidget *YassLabel_inscrinom;
  GtkWidget *YassLabel_prenom;
  GtkWidget *YassLabel_inscripasswd;
  GtkWidget *Y_button_inscription_V;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image6;
  GtkWidget *label30;
  GtkWidget *Y_label_subscription;

  YassInscriWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassInscriWind), _("Inscription"));

  YassfixedInscri = gtk_fixed_new ();
  gtk_widget_show (YassfixedInscri);
  gtk_container_add (GTK_CONTAINER (YassInscriWind), YassfixedInscri);

  Y_entry_insc_nom = gtk_entry_new ();
  gtk_widget_show (Y_entry_insc_nom);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_entry_insc_nom, 232, 104);
  gtk_widget_set_size_request (Y_entry_insc_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Y_entry_insc_nom), 8226);

  Y_entry_insc_prenom = gtk_entry_new ();
  gtk_widget_show (Y_entry_insc_prenom);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_entry_insc_prenom, 232, 136);
  gtk_widget_set_size_request (Y_entry_insc_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Y_entry_insc_prenom), 8226);

  Y_entry_insc_login = gtk_entry_new ();
  gtk_widget_show (Y_entry_insc_login);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_entry_insc_login, 232, 168);
  gtk_widget_set_size_request (Y_entry_insc_login, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Y_entry_insc_login), 8226);

  Y_entry_insc_pwd = gtk_entry_new ();
  gtk_widget_show (Y_entry_insc_pwd);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_entry_insc_pwd, 232, 200);
  gtk_widget_set_size_request (Y_entry_insc_pwd, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Y_entry_insc_pwd), 8226);

  Y_entry_insc_ = gtk_entry_new ();
  gtk_widget_show (Y_entry_insc_);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_entry_insc_, 232, 232);
  gtk_widget_set_size_request (Y_entry_insc_, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Y_entry_insc_), 8226);

  Y_spinbutton_Idnj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  Y_spinbutton_Idnj = gtk_spin_button_new (GTK_ADJUSTMENT (Y_spinbutton_Idnj_adj), 1, 0);
  gtk_widget_show (Y_spinbutton_Idnj);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_spinbutton_Idnj, 240, 288);
  gtk_widget_set_size_request (Y_spinbutton_Idnj, 60, 27);

  Y_spinbutton_idnm_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  Y_spinbutton_idnm = gtk_spin_button_new (GTK_ADJUSTMENT (Y_spinbutton_idnm_adj), 1, 0);
  gtk_widget_show (Y_spinbutton_idnm);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_spinbutton_idnm, 344, 288);
  gtk_widget_set_size_request (Y_spinbutton_idnm, 60, 27);

  Y_spinbutton_idna_adj = gtk_adjustment_new (1, 1950, 2001, 1, 10, 10);
  Y_spinbutton_idna = gtk_spin_button_new (GTK_ADJUSTMENT (Y_spinbutton_idna_adj), 1, 0);
  gtk_widget_show (Y_spinbutton_idna);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_spinbutton_idna, 456, 288);
  gtk_widget_set_size_request (Y_spinbutton_idna, 60, 27);

  YassLabel_inscriDN = gtk_label_new (_("Date de naissance "));
  gtk_widget_show (YassLabel_inscriDN);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), YassLabel_inscriDN, 64, 296);
  gtk_widget_set_size_request (YassLabel_inscriDN, 153, 16);

  YassLabel_inscrilogin = gtk_label_new (_("Login"));
  gtk_widget_show (YassLabel_inscrilogin);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), YassLabel_inscrilogin, 136, 176);
  gtk_widget_set_size_request (YassLabel_inscrilogin, 49, 17);

  Y_entry_insc_cin = gtk_label_new (_("CIN"));
  gtk_widget_show (Y_entry_insc_cin);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_entry_insc_cin, 128, 240);
  gtk_widget_set_size_request (Y_entry_insc_cin, 49, 17);

  YassLabel_inscrinom = gtk_label_new (_("Nom"));
  gtk_widget_show (YassLabel_inscrinom);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), YassLabel_inscrinom, 112, 104);
  gtk_widget_set_size_request (YassLabel_inscrinom, 104, 25);

  YassLabel_prenom = gtk_label_new (_("Prenom"));
  gtk_widget_show (YassLabel_prenom);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), YassLabel_prenom, 128, 144);
  gtk_widget_set_size_request (YassLabel_prenom, 80, 16);

  YassLabel_inscripasswd = gtk_label_new (_("Mot de passe "));
  gtk_widget_show (YassLabel_inscripasswd);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), YassLabel_inscripasswd, 104, 208);
  gtk_widget_set_size_request (YassLabel_inscripasswd, 112, 16);

  Y_button_inscription_V = gtk_button_new ();
  gtk_widget_show (Y_button_inscription_V);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_button_inscription_V, 528, 400);
  gtk_widget_set_size_request (Y_button_inscription_V, 104, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (Y_button_inscription_V), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox7), image6, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox7), label30, FALSE, FALSE, 0);

  Y_label_subscription = gtk_label_new (_("Bienvenue , Dans notre agence !"));
  gtk_widget_show (Y_label_subscription);
  gtk_fixed_put (GTK_FIXED (YassfixedInscri), Y_label_subscription, 0, 16);
  gtk_widget_set_size_request (Y_label_subscription, 728, 40);

  g_signal_connect ((gpointer) Y_button_inscription_V, "clicked",
                    G_CALLBACK (on_Y_button_inscription_V_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassInscriWind, YassInscriWind, "YassInscriWind");
  GLADE_HOOKUP_OBJECT (YassInscriWind, YassfixedInscri, "YassfixedInscri");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_entry_insc_nom, "Y_entry_insc_nom");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_entry_insc_prenom, "Y_entry_insc_prenom");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_entry_insc_login, "Y_entry_insc_login");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_entry_insc_pwd, "Y_entry_insc_pwd");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_entry_insc_, "Y_entry_insc_");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_spinbutton_Idnj, "Y_spinbutton_Idnj");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_spinbutton_idnm, "Y_spinbutton_idnm");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_spinbutton_idna, "Y_spinbutton_idna");
  GLADE_HOOKUP_OBJECT (YassInscriWind, YassLabel_inscriDN, "YassLabel_inscriDN");
  GLADE_HOOKUP_OBJECT (YassInscriWind, YassLabel_inscrilogin, "YassLabel_inscrilogin");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_entry_insc_cin, "Y_entry_insc_cin");
  GLADE_HOOKUP_OBJECT (YassInscriWind, YassLabel_inscrinom, "YassLabel_inscrinom");
  GLADE_HOOKUP_OBJECT (YassInscriWind, YassLabel_prenom, "YassLabel_prenom");
  GLADE_HOOKUP_OBJECT (YassInscriWind, YassLabel_inscripasswd, "YassLabel_inscripasswd");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_button_inscription_V, "Y_button_inscription_V");
  GLADE_HOOKUP_OBJECT (YassInscriWind, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (YassInscriWind, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (YassInscriWind, image6, "image6");
  GLADE_HOOKUP_OBJECT (YassInscriWind, label30, "label30");
  GLADE_HOOKUP_OBJECT (YassInscriWind, Y_label_subscription, "Y_label_subscription");

  return YassInscriWind;
}

GtkWidget*
create_YasswindowGestion (void)
{
  GtkWidget *YasswindowGestion;
  GtkWidget *Yassfixed_GestWind;
  GtkWidget *YassbuttonEx_GestWind;
  GtkWidget *YassbuttonVols_GestWind;
  GtkWidget *YassbuttonHtls_GestWind;
  GtkWidget *YassbuttonAvezVousRec;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *Yassimg_Botn_AvezvousRec;
  GtkWidget *Yasslabel_Botn_AvezvousRec;
  GtkWidget *y_button_backtoMainWind;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image10;
  GtkWidget *label37;
  GtkWidget *YassbuttonVoit_GestWind;
  GtkWidget *label35;

  YasswindowGestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YasswindowGestion), _("Gestion"));

  Yassfixed_GestWind = gtk_fixed_new ();
  gtk_widget_show (Yassfixed_GestWind);
  gtk_container_add (GTK_CONTAINER (YasswindowGestion), Yassfixed_GestWind);

  YassbuttonEx_GestWind = gtk_button_new_with_mnemonic (_("Excursions"));
  gtk_widget_show (YassbuttonEx_GestWind);
  gtk_fixed_put (GTK_FIXED (Yassfixed_GestWind), YassbuttonEx_GestWind, 208, 184);
  gtk_widget_set_size_request (YassbuttonEx_GestWind, 170, 45);

  YassbuttonVols_GestWind = gtk_button_new_with_mnemonic (_("Vols"));
  gtk_widget_show (YassbuttonVols_GestWind);
  gtk_fixed_put (GTK_FIXED (Yassfixed_GestWind), YassbuttonVols_GestWind, 240, 128);
  gtk_widget_set_size_request (YassbuttonVols_GestWind, 104, 24);

  YassbuttonHtls_GestWind = gtk_button_new_with_mnemonic (_("Hotels"));
  gtk_widget_show (YassbuttonHtls_GestWind);
  gtk_fixed_put (GTK_FIXED (Yassfixed_GestWind), YassbuttonHtls_GestWind, 256, 96);
  gtk_widget_set_size_request (YassbuttonHtls_GestWind, 72, 32);

  YassbuttonAvezVousRec = gtk_button_new ();
  gtk_widget_show (YassbuttonAvezVousRec);
  gtk_fixed_put (GTK_FIXED (Yassfixed_GestWind), YassbuttonAvezVousRec, 432, 0);
  gtk_widget_set_size_request (YassbuttonAvezVousRec, 258, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (YassbuttonAvezVousRec), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  Yassimg_Botn_AvezvousRec = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (Yassimg_Botn_AvezvousRec);
  gtk_box_pack_start (GTK_BOX (hbox11), Yassimg_Botn_AvezvousRec, FALSE, FALSE, 0);

  Yasslabel_Botn_AvezvousRec = gtk_label_new_with_mnemonic (_("Avez-vous une Reclamation ?"));
  gtk_widget_show (Yasslabel_Botn_AvezvousRec);
  gtk_box_pack_start (GTK_BOX (hbox11), Yasslabel_Botn_AvezvousRec, FALSE, FALSE, 0);

  y_button_backtoMainWind = gtk_button_new ();
  gtk_widget_show (y_button_backtoMainWind);
  gtk_fixed_put (GTK_FIXED (Yassfixed_GestWind), y_button_backtoMainWind, 560, 272);
  gtk_widget_set_size_request (y_button_backtoMainWind, 162, 37);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (y_button_backtoMainWind), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox12), image10, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox12), label37, FALSE, FALSE, 0);

  YassbuttonVoit_GestWind = gtk_button_new_with_mnemonic (_("Voitures"));
  gtk_widget_show (YassbuttonVoit_GestWind);
  gtk_fixed_put (GTK_FIXED (Yassfixed_GestWind), YassbuttonVoit_GestWind, 224, 152);
  gtk_widget_set_size_request (YassbuttonVoit_GestWind, 136, 32);

  label35 = gtk_label_new (_("goodnight "));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (Yassfixed_GestWind), label35, 0, 288);
  gtk_widget_set_size_request (label35, 240, 17);

  g_signal_connect ((gpointer) YassbuttonAvezVousRec, "clicked",
                    G_CALLBACK (on_YassbuttonAvezVousRec_clicked),
                    NULL);
  g_signal_connect ((gpointer) y_button_backtoMainWind, "clicked",
                    G_CALLBACK (on_y_button_backtoMainWind_clicked),
                    NULL);
  g_signal_connect ((gpointer) YassbuttonVoit_GestWind, "clicked",
                    G_CALLBACK (on_YassbuttonVoit_GestWind_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YasswindowGestion, YasswindowGestion, "YasswindowGestion");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, Yassfixed_GestWind, "Yassfixed_GestWind");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, YassbuttonEx_GestWind, "YassbuttonEx_GestWind");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, YassbuttonVols_GestWind, "YassbuttonVols_GestWind");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, YassbuttonHtls_GestWind, "YassbuttonHtls_GestWind");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, YassbuttonAvezVousRec, "YassbuttonAvezVousRec");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, Yassimg_Botn_AvezvousRec, "Yassimg_Botn_AvezvousRec");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, Yasslabel_Botn_AvezvousRec, "Yasslabel_Botn_AvezvousRec");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, y_button_backtoMainWind, "y_button_backtoMainWind");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, image10, "image10");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, label37, "label37");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, YassbuttonVoit_GestWind, "YassbuttonVoit_GestWind");
  GLADE_HOOKUP_OBJECT (YasswindowGestion, label35, "label35");

  return YasswindowGestion;
}

GtkWidget*
create_YassAfficherVosRecWind (void)
{
  GtkWidget *YassAfficherVosRecWind;
  GtkWidget *Y_fixed_VotreRec;
  GtkWidget *Yasstreeview_VosRec;
  GtkWidget *Yasslabel_VotreRec;
  GtkWidget *button_Retour_VosRec__EspaceResC;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *Y_imgBotn_Retour_VosrRec__EspResC;
  GtkWidget *Yasslabel_Botn_RetourVosRec__EspResC;
  GtkWidget *Yassbutton_Supp_VosRec;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *Yass_imgbtn_Supp_VosRec;
  GtkWidget *Yass_labelbtn_Supp_VosRec;
  GtkWidget *Y_label_selectionner_modifier;
  GtkWidget *Yassbutton_Modif_VosRec;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *Yass_imgbtn_Modifier_VosRec;
  GtkWidget *Yass_labelbtn_Modif_VosRec;

  YassAfficherVosRecWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassAfficherVosRecWind), _("Vos reclamations"));

  Y_fixed_VotreRec = gtk_fixed_new ();
  gtk_widget_show (Y_fixed_VotreRec);
  gtk_container_add (GTK_CONTAINER (YassAfficherVosRecWind), Y_fixed_VotreRec);

  Yasstreeview_VosRec = gtk_tree_view_new ();
  gtk_widget_show (Yasstreeview_VosRec);
  gtk_fixed_put (GTK_FIXED (Y_fixed_VotreRec), Yasstreeview_VosRec, 32, 112);
  gtk_widget_set_size_request (Yasstreeview_VosRec, 680, 304);

  Yasslabel_VotreRec = gtk_label_new (_("Vos r\303\251clamations"));
  gtk_widget_show (Yasslabel_VotreRec);
  gtk_fixed_put (GTK_FIXED (Y_fixed_VotreRec), Yasslabel_VotreRec, 208, -16);
  gtk_widget_set_size_request (Yasslabel_VotreRec, 216, 64);

  button_Retour_VosRec__EspaceResC = gtk_button_new ();
  gtk_widget_show (button_Retour_VosRec__EspaceResC);
  gtk_fixed_put (GTK_FIXED (Y_fixed_VotreRec), button_Retour_VosRec__EspaceResC, 568, 568);
  gtk_widget_set_size_request (button_Retour_VosRec__EspaceResC, 98, 37);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_Retour_VosRec__EspaceResC), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  Y_imgBotn_Retour_VosrRec__EspResC = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (Y_imgBotn_Retour_VosrRec__EspResC);
  gtk_box_pack_start (GTK_BOX (hbox16), Y_imgBotn_Retour_VosrRec__EspResC, FALSE, FALSE, 0);

  Yasslabel_Botn_RetourVosRec__EspResC = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (Yasslabel_Botn_RetourVosRec__EspResC);
  gtk_box_pack_start (GTK_BOX (hbox16), Yasslabel_Botn_RetourVosRec__EspResC, FALSE, FALSE, 0);

  Yassbutton_Supp_VosRec = gtk_button_new ();
  gtk_widget_show (Yassbutton_Supp_VosRec);
  gtk_fixed_put (GTK_FIXED (Y_fixed_VotreRec), Yassbutton_Supp_VosRec, 488, 520);
  gtk_widget_set_size_request (Yassbutton_Supp_VosRec, 120, 37);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (Yassbutton_Supp_VosRec), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  Yass_imgbtn_Supp_VosRec = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (Yass_imgbtn_Supp_VosRec);
  gtk_box_pack_start (GTK_BOX (hbox21), Yass_imgbtn_Supp_VosRec, FALSE, FALSE, 0);

  Yass_labelbtn_Supp_VosRec = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (Yass_labelbtn_Supp_VosRec);
  gtk_box_pack_start (GTK_BOX (hbox21), Yass_labelbtn_Supp_VosRec, FALSE, FALSE, 0);

  Y_label_selectionner_modifier = gtk_label_new (_("Selectionner une reclamation a modifier"));
  gtk_widget_show (Y_label_selectionner_modifier);
  gtk_fixed_put (GTK_FIXED (Y_fixed_VotreRec), Y_label_selectionner_modifier, 176, 72);
  gtk_widget_set_size_request (Y_label_selectionner_modifier, 304, 25);

  Yassbutton_Modif_VosRec = gtk_button_new ();
  gtk_widget_show (Yassbutton_Modif_VosRec);
  gtk_fixed_put (GTK_FIXED (Y_fixed_VotreRec), Yassbutton_Modif_VosRec, 624, 520);
  gtk_widget_set_size_request (Yassbutton_Modif_VosRec, 112, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (Yassbutton_Modif_VosRec), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  Yass_imgbtn_Modifier_VosRec = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (Yass_imgbtn_Modifier_VosRec);
  gtk_box_pack_start (GTK_BOX (hbox15), Yass_imgbtn_Modifier_VosRec, FALSE, FALSE, 0);

  Yass_labelbtn_Modif_VosRec = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (Yass_labelbtn_Modif_VosRec);
  gtk_box_pack_start (GTK_BOX (hbox15), Yass_labelbtn_Modif_VosRec, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Yasstreeview_VosRec, "row_activated",
                    G_CALLBACK (on_Yasstreeview_VosRec_columns_changed),
                    NULL);
  g_signal_connect ((gpointer) button_Retour_VosRec__EspaceResC, "clicked",
                    G_CALLBACK (on_button_Retour_VosRec__EspaceResC_clicked),
                    NULL);
  g_signal_connect ((gpointer) Yassbutton_Supp_VosRec, "clicked",
                    G_CALLBACK (on_Yassbutton_Supp_VosRec_clicked),
                    NULL);
  g_signal_connect ((gpointer) Yassbutton_Modif_VosRec, "clicked",
                    G_CALLBACK (on_Yassbutton_Modif_VosRec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassAfficherVosRecWind, YassAfficherVosRecWind, "YassAfficherVosRecWind");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Y_fixed_VotreRec, "Y_fixed_VotreRec");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yasstreeview_VosRec, "Yasstreeview_VosRec");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yasslabel_VotreRec, "Yasslabel_VotreRec");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, button_Retour_VosRec__EspaceResC, "button_Retour_VosRec__EspaceResC");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Y_imgBotn_Retour_VosrRec__EspResC, "Y_imgBotn_Retour_VosrRec__EspResC");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yasslabel_Botn_RetourVosRec__EspResC, "Yasslabel_Botn_RetourVosRec__EspResC");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yassbutton_Supp_VosRec, "Yassbutton_Supp_VosRec");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yass_imgbtn_Supp_VosRec, "Yass_imgbtn_Supp_VosRec");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yass_labelbtn_Supp_VosRec, "Yass_labelbtn_Supp_VosRec");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Y_label_selectionner_modifier, "Y_label_selectionner_modifier");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yassbutton_Modif_VosRec, "Yassbutton_Modif_VosRec");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yass_imgbtn_Modifier_VosRec, "Yass_imgbtn_Modifier_VosRec");
  GLADE_HOOKUP_OBJECT (YassAfficherVosRecWind, Yass_labelbtn_Modif_VosRec, "Yass_labelbtn_Modif_VosRec");

  return YassAfficherVosRecWind;
}

GtkWidget*
create_YassEspaceAdminWind (void)
{
  GtkWidget *YassEspaceAdminWind;
  GtkWidget *Y_fixed_EspaceAdminMainWind;
  GtkWidget *Yasslabeldescriptifadmin;
  GtkWidget *Y_button_EspaceRecAdmin;

  YassEspaceAdminWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassEspaceAdminWind), _("Espace Admin"));

  Y_fixed_EspaceAdminMainWind = gtk_fixed_new ();
  gtk_widget_show (Y_fixed_EspaceAdminMainWind);
  gtk_container_add (GTK_CONTAINER (YassEspaceAdminWind), Y_fixed_EspaceAdminMainWind);

  Yasslabeldescriptifadmin = gtk_label_new (_("label42"));
  gtk_widget_show (Yasslabeldescriptifadmin);
  gtk_fixed_put (GTK_FIXED (Y_fixed_EspaceAdminMainWind), Yasslabeldescriptifadmin, 112, 344);
  gtk_widget_set_size_request (Yasslabeldescriptifadmin, 49, 17);

  Y_button_EspaceRecAdmin = gtk_button_new_with_mnemonic (_("Gestion des reclamations"));
  gtk_widget_show (Y_button_EspaceRecAdmin);
  gtk_fixed_put (GTK_FIXED (Y_fixed_EspaceAdminMainWind), Y_button_EspaceRecAdmin, 96, 88);
  gtk_widget_set_size_request (Y_button_EspaceRecAdmin, 194, 64);

  g_signal_connect ((gpointer) Y_button_EspaceRecAdmin, "clicked",
                    G_CALLBACK (on_Y_button_EspaceRecAdmin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassEspaceAdminWind, YassEspaceAdminWind, "YassEspaceAdminWind");
  GLADE_HOOKUP_OBJECT (YassEspaceAdminWind, Y_fixed_EspaceAdminMainWind, "Y_fixed_EspaceAdminMainWind");
  GLADE_HOOKUP_OBJECT (YassEspaceAdminWind, Yasslabeldescriptifadmin, "Yasslabeldescriptifadmin");
  GLADE_HOOKUP_OBJECT (YassEspaceAdminWind, Y_button_EspaceRecAdmin, "Y_button_EspaceRecAdmin");

  return YassEspaceAdminWind;
}

GtkWidget*
create_YassEspaceAgentWind (void)
{
  GtkWidget *YassEspaceAgentWind;
  GtkWidget *fixed6;
  GtkWidget *Yasslabeldescriptifagent;
  GtkWidget *Y_button_EspaceRecAgent;

  YassEspaceAgentWind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YassEspaceAgentWind), _("Espace Agent"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (YassEspaceAgentWind), fixed6);

  Yasslabeldescriptifagent = gtk_label_new (_("label43"));
  gtk_widget_show (Yasslabeldescriptifagent);
  gtk_fixed_put (GTK_FIXED (fixed6), Yasslabeldescriptifagent, 80, 328);
  gtk_widget_set_size_request (Yasslabeldescriptifagent, 49, 17);

  Y_button_EspaceRecAgent = gtk_button_new_with_mnemonic (_("Gestion des reclamations"));
  gtk_widget_show (Y_button_EspaceRecAgent);
  gtk_fixed_put (GTK_FIXED (fixed6), Y_button_EspaceRecAgent, 88, 88);
  gtk_widget_set_size_request (Y_button_EspaceRecAgent, 210, 56);

  g_signal_connect ((gpointer) Y_button_EspaceRecAgent, "clicked",
                    G_CALLBACK (on_Y_button_EspaceRecAgent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassEspaceAgentWind, YassEspaceAgentWind, "YassEspaceAgentWind");
  GLADE_HOOKUP_OBJECT (YassEspaceAgentWind, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (YassEspaceAgentWind, Yasslabeldescriptifagent, "Yasslabeldescriptifagent");
  GLADE_HOOKUP_OBJECT (YassEspaceAgentWind, Y_button_EspaceRecAgent, "Y_button_EspaceRecAgent");

  return YassEspaceAgentWind;
}

GtkWidget*
create_YassReserverVoiture (void)
{
  GtkWidget *YassReserverVoiture;
  GtkWidget *fixed7;
  GtkWidget *button6;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image13;
  GtkWidget *label47;
  GtkWidget *button7;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image14;
  GtkWidget *label48;
  GtkWidget *label86;
  GtkWidget *notebook2;
  GtkWidget *fixed8;
  GtkWidget *entry4;
  GtkWidget *calendar3;
  GtkWidget *calendar4;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *ybuttonreserver;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image15;
  GtkWidget *label56;
  GtkWidget *combobox3;
  GtkWidget *combobox4;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label38;
  GtkWidget *label550;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label31;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label5933;
  GtkWidget *label35;
  GtkWidget *label64;
  GtkWidget *fixed9;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview2;
  GtkWidget *label76;
  GtkWidget *ybutton_modifier_car;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image17;
  GtkWidget *label75;
  GtkWidget *ybutton_suppcar;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image16;
  GtkWidget *label71;
  GtkWidget *combobox7;
  GtkWidget *combobox6;
  GtkWidget *label60;
  GtkWidget *label55;
  GtkWidget *label59;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label68;
  GtkWidget *label78555;
  GtkWidget *label67;
  GtkWidget *label78;
  GtkWidget *fixed10;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview4;
  GtkWidget *entry8;
  GtkWidget *label83;
  GtkWidget *label79;
  GtkWidget *label70;
  GtkWidget *label72;
  GtkWidget *y_button_rechcar;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image18;
  GtkWidget *label80;
  GtkWidget *label84;

  YassReserverVoiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (YassReserverVoiture, 1000, 700);
  gtk_container_set_border_width (GTK_CONTAINER (YassReserverVoiture), 1);
  gtk_window_set_title (GTK_WINDOW (YassReserverVoiture), _("reservervoiture"));
  gtk_window_set_position (GTK_WINDOW (YassReserverVoiture), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (YassReserverVoiture), FALSE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (YassReserverVoiture), fixed7);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed7), button6, 888, 640);
  gtk_widget_set_size_request (button6, 96, 53);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button6), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image13 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox22), image13, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox22), label47, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed7), button7, 16, 640);
  gtk_widget_set_size_request (button7, 96, 53);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button7), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox23), image14, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox23), label48, FALSE, FALSE, 0);

  label86 = gtk_label_new (_("Developed with <3 by yassin adalet"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed7), label86, 368, 640);
  gtk_widget_set_size_request (label86, 304, 48);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed7), notebook2, 0, 0);
  gtk_widget_set_size_request (notebook2, 1008, 640);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed8);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed8), entry4, 272, 112);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  calendar3 = gtk_calendar_new ();
  gtk_widget_show (calendar3);
  gtk_fixed_put (GTK_FIXED (fixed8), calendar3, 232, 216);
  gtk_widget_set_size_request (calendar3, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar3),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendar4 = gtk_calendar_new ();
  gtk_widget_show (calendar4);
  gtk_fixed_put (GTK_FIXED (fixed8), calendar4, 696, 216);
  gtk_widget_set_size_request (calendar4, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar4),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton6_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton6, 440, 456);
  gtk_widget_set_size_request (spinbutton6, 88, 27);

  ybuttonreserver = gtk_button_new ();
  gtk_widget_show (ybuttonreserver);
  gtk_fixed_put (GTK_FIXED (fixed8), ybuttonreserver, 768, 496);
  gtk_widget_set_size_request (ybuttonreserver, 96, 53);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (ybuttonreserver), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image15 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox24), image15, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox24), label56, FALSE, FALSE, 0);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox3, 144, 160);
  gtk_widget_set_size_request (combobox3, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Algerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Marroc"));

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox4, 600, 160);
  gtk_widget_set_size_request (combobox4, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Algerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Marroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Etat-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Italie"));

  label39 = gtk_label_new (_("Model : "));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed8), label39, 24, 152);
  gtk_widget_set_size_request (label39, 128, 48);

  label40 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Model !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label40, 256, 144);
  gtk_widget_set_size_request (label40, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  label38 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir id !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label38, 440, 88);
  gtk_widget_set_size_request (label38, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label550 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label550);
  gtk_fixed_put (GTK_FIXED (fixed8), label550, 344, 440);
  gtk_widget_set_size_request (label550, 128, 56);

  label36 = gtk_label_new (_("<span foreground=\"green\"><b>Voiture reserv\303\251e</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label36, 208, 16);
  gtk_widget_set_size_request (label36, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label37 = gtk_label_new (_("<span foreground=\"grey\"><b>Voiture non disponible !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label37, 440, 16);
  gtk_widget_set_size_request (label37, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label31 = gtk_label_new (_("Id : "));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed8), label31, 88, 104);
  gtk_widget_set_size_request (label31, 80, 48);

  label51 = gtk_label_new (_("Date d\303\251but  : "));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed8), label51, 88, 264);
  gtk_widget_set_size_request (label51, 128, 48);

  label52 = gtk_label_new (_("Date fin : "));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed8), label52, 552, 280);
  gtk_widget_set_size_request (label52, 128, 48);

  label5933 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Marque  !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label5933, 736, 136);
  gtk_widget_set_size_request (label5933, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label5933), TRUE);

  label35 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed8), label35, 472, 152);
  gtk_widget_set_size_request (label35, 128, 48);

  label64 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label64);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label64);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed9);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed9), entry5, 792, 216);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed9), entry6, 792, 264);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  spinbutton8_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton8, 840, 328);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed9), scrolledwindow1, 0, 88);
  gtk_widget_set_size_request (scrolledwindow1, 584, 384);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview2);
  gtk_widget_set_size_request (treeview2, 584, 384);

  label76 = gtk_label_new ("");
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed9), label76, 784, 72);
  gtk_widget_set_size_request (label76, 104, 48);

  ybutton_modifier_car = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), ybutton_modifier_car, 824, 424);
  gtk_widget_set_size_request (ybutton_modifier_car, 96, 53);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (ybutton_modifier_car), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image17 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox26), image17, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox26), label75, FALSE, FALSE, 0);

  ybutton_suppcar = gtk_button_new ();
  gtk_widget_show (ybutton_suppcar);
  gtk_fixed_put (GTK_FIXED (fixed9), ybutton_suppcar, 208, 496);
  gtk_widget_set_size_request (ybutton_suppcar, 104, 56);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (ybutton_suppcar), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox25), image16, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox25), label71, FALSE, FALSE, 0);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox7, 784, 120);
  gtk_widget_set_size_request (combobox7, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Algerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Marroc"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox6, 784, 160);
  gtk_widget_set_size_request (combobox6, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Algerie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Marroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Etat-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Italie"));

  label60 = gtk_label_new (_("<span foreground=\"blue\"><i>reservation modifi\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), label60, 664, 0);
  gtk_widget_set_size_request (label60, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);

  label55 = gtk_label_new (_("<span foreground=\"orange\"><b>Modifier la reservation !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), label55, 648, 72);
  gtk_widget_set_size_request (label55, 184, 48);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  label59 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner une reservation !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), label59, 0, 16);
  gtk_widget_set_size_request (label59, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  label65 = gtk_label_new (_("Mod\303\251le :"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed9), label65, 664, 112);
  gtk_widget_set_size_request (label65, 128, 48);

  label66 = gtk_label_new (_("Marque  : "));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed9), label66, 664, 152);
  gtk_widget_set_size_request (label66, 128, 48);

  label68 = gtk_label_new (_("Date de fin : "));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed9), label68, 656, 256);
  gtk_widget_set_size_request (label68, 128, 48);

  label78555 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label78555);
  gtk_fixed_put (GTK_FIXED (fixed9), label78555, 728, 320);
  gtk_widget_set_size_request (label78555, 128, 48);

  label67 = gtk_label_new (_("Date de debut : "));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed9), label67, 656, 208);
  gtk_widget_set_size_request (label67, 128, 48);

  label78 = gtk_label_new (_("Afficher/Supprimer/Modifier"));
  gtk_widget_show (label78);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label78);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed10);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed10), scrolledwindow2, 0, 48);
  gtk_widget_set_size_request (scrolledwindow2, 592, 344);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview4);
  gtk_widget_set_size_request (treeview4, 592, 344);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed10), entry8, 744, 160);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label83 = gtk_label_new ("");
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed10), label83, 688, 224);
  gtk_widget_set_size_request (label83, 72, 56);

  label79 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed10), label79, 600, 152);
  gtk_widget_set_size_request (label79, 128, 48);

  label70 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Marque !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), label70, 656, 72);
  gtk_widget_set_size_request (label70, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label70), TRUE);

  label72 = gtk_label_new (_("<span foreground=\"green\"><b>Resulta(s) trouv\303\251e(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), label72, 704, 216);
  gtk_widget_set_size_request (label72, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label72), TRUE);

  y_button_rechcar = gtk_button_new ();
  gtk_widget_show (y_button_rechcar);
  gtk_fixed_put (GTK_FIXED (fixed10), y_button_rechcar, 752, 360);
  gtk_widget_set_size_request (y_button_rechcar, 96, 53);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (y_button_rechcar), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image18 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox27), image18, FALSE, FALSE, 0);

  label80 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label80);
  gtk_box_pack_start (GTK_BOX (hbox27), label80, FALSE, FALSE, 0);

  label84 = gtk_label_new (_("Chercher"));
  gtk_widget_show (label84);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label84);

  g_signal_connect ((gpointer) ybuttonreserver, "clicked",
                    G_CALLBACK (on_ybutton_ajoutercar_clicked),
                    NULL);
  g_signal_connect ((gpointer) ybutton_modifier_car, "clicked",
                    G_CALLBACK (on_ybutton_modifier_car_clicked),
                    NULL);
  g_signal_connect ((gpointer) ybutton_suppcar, "clicked",
                    G_CALLBACK (on_ybutton_suppcar_clicked),
                    NULL);
  g_signal_connect ((gpointer) y_button_rechcar, "clicked",
                    G_CALLBACK (on_y_button_rechcar_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YassReserverVoiture, YassReserverVoiture, "YassReserverVoiture");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, button6, "button6");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, image13, "image13");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label47, "label47");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, button7, "button7");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, image14, "image14");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label48, "label48");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label86, "label86");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, calendar3, "calendar3");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, calendar4, "calendar4");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, ybuttonreserver, "ybuttonreserver");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, image15, "image15");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label56, "label56");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label39, "label39");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label40, "label40");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label38, "label38");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label550, "label550");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label36, "label36");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label37, "label37");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label31, "label31");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label51, "label51");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label52, "label52");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label5933, "label5933");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label35, "label35");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label64, "label64");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label76, "label76");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, ybutton_modifier_car, "ybutton_modifier_car");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, image17, "image17");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label75, "label75");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, ybutton_suppcar, "ybutton_suppcar");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, image16, "image16");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label71, "label71");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label60, "label60");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label55, "label55");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label59, "label59");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label65, "label65");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label66, "label66");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label68, "label68");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label78555, "label78555");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label67, "label67");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label78, "label78");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label83, "label83");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label79, "label79");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label70, "label70");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label72, "label72");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, y_button_rechcar, "y_button_rechcar");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, image18, "image18");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label80, "label80");
  GLADE_HOOKUP_OBJECT (YassReserverVoiture, label84, "label84");

  return YassReserverVoiture;
}

