/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowgestionclient (void);
GtkWidget* create_windowAjouterclient (void);
GtkWidget* create_windowModifierclient (void);
GtkWidget* create_windowreserverexcursionadmin (void);
GtkWidget* create_windowreserverexcursion_client (void);
