/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowgestionclient (void)
{
  GtkWidget *windowgestionclient;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *hbuttonbox1;
  GtkWidget *entry13;
  GtkWidget *button7;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label43;
  GtkWidget *label42;
  GtkWidget *button4;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label4;
  GtkWidget *button5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label5;
  GtkWidget *button6;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label6;
  GtkWidget *button3;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;

  windowgestionclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowgestionclient), _("gestion client"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowgestionclient), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 344, 184);
  gtk_widget_set_size_request (treeview1, 494, 265);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed1), hbuttonbox1, 640, 432);
  gtk_widget_set_size_request (hbuttonbox1, 255, 29);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed1), entry13, 672, 120);
  gtk_widget_set_size_request (entry13, 169, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed1), button7, 704, 88);
  gtk_widget_set_size_request (button7, 100, 30);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button7), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox20), label43, FALSE, FALSE, 0);

  label42 = gtk_label_new (_("Gestion des clients"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed1), label42, 296, 136);
  gtk_widget_set_size_request (label42, 224, 37);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 544, 472);
  gtk_widget_set_size_request (button4, 100, 30);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button4), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modifer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1), button5, 680, 472);
  gtk_widget_set_size_request (button5, 100, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed1), button6, 344, 48);
  gtk_widget_set_size_request (button6, 100, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button6), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 408, 472);
  gtk_widget_set_size_request (button3, 100, 30);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button3), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_modifier_gestion_client_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_supprimer_gestion_client_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_retour_gestion_client_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_ajouter_gestion_client_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowgestionclient, windowgestionclient, "windowgestionclient");
  GLADE_HOOKUP_OBJECT (windowgestionclient, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowgestionclient, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowgestionclient, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (windowgestionclient, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (windowgestionclient, button7, "button7");
  GLADE_HOOKUP_OBJECT (windowgestionclient, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (windowgestionclient, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (windowgestionclient, image20, "image20");
  GLADE_HOOKUP_OBJECT (windowgestionclient, label43, "label43");
  GLADE_HOOKUP_OBJECT (windowgestionclient, label42, "label42");
  GLADE_HOOKUP_OBJECT (windowgestionclient, button4, "button4");
  GLADE_HOOKUP_OBJECT (windowgestionclient, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowgestionclient, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowgestionclient, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowgestionclient, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowgestionclient, button5, "button5");
  GLADE_HOOKUP_OBJECT (windowgestionclient, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowgestionclient, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowgestionclient, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowgestionclient, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowgestionclient, button6, "button6");
  GLADE_HOOKUP_OBJECT (windowgestionclient, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowgestionclient, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowgestionclient, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowgestionclient, label6, "label6");
  GLADE_HOOKUP_OBJECT (windowgestionclient, button3, "button3");
  GLADE_HOOKUP_OBJECT (windowgestionclient, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowgestionclient, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowgestionclient, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowgestionclient, label3, "label3");

  return windowgestionclient;
}

GtkWidget*
create_windowAjouterclient (void)
{
  GtkWidget *windowAjouterclient;
  GtkWidget *fixed2;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *entry3;
  GtkWidget *label12;
  GtkWidget *entry4;
  GtkWidget *label13;
  GtkWidget *entry5;
  GtkWidget *label14;
  GtkWidget *entry6;
  GtkWidget *label15;
  GtkWidget *label9;
  GtkWidget *label8;
  GtkWidget *button10;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label16;
  GtkWidget *button8;

  windowAjouterclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowAjouterclient), _("Ajout client"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowAjouterclient), fixed2);

  spinbutton1_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 696, 272);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 760, 272);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1900, 1900, 2019, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 824, 272);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 584, 208);
  gtk_widget_set_size_request (entry1, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 584, 240);
  gtk_widget_set_size_request (entry2, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label10 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 440, 240);
  gtk_widget_set_size_request (label10, 106, 25);

  label11 = gtk_label_new (_("Date de naissance (jj/mm/aaaa)"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 440, 272);
  gtk_widget_set_size_request (label11, 262, 28);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 584, 304);
  gtk_widget_set_size_request (entry3, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label12 = gtk_label_new (_("Nom_utilisateur"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 440, 304);
  gtk_widget_set_size_request (label12, 162, 27);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 584, 336);
  gtk_widget_set_size_request (entry4, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label13 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 440, 336);
  gtk_widget_set_size_request (label13, 142, 30);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 584, 368);
  gtk_widget_set_size_request (entry5, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label14 = gtk_label_new (_("Confirmer"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 440, 368);
  gtk_widget_set_size_request (label14, 121, 30);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry6, 584, 400);
  gtk_widget_set_size_request (entry6, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label15 = gtk_label_new (_("CIN"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 440, 400);
  gtk_widget_set_size_request (label15, 77, 30);

  label9 = gtk_label_new (_("Ajouter un client"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 648, 152);
  gtk_widget_set_size_request (label9, 129, 27);

  label8 = gtk_label_new (_("Nom client "));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 448, 208);
  gtk_widget_set_size_request (label8, 111, 25);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed2), button10, 464, 96);
  gtk_widget_set_size_request (button10, 98, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button10), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox6), label16, FALSE, FALSE, 0);

  button8 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 584, 440);
  gtk_widget_set_size_request (button8, 100, 30);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_retour_ajouter_client_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_ajouter_ajouter_client_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjouterclient, windowAjouterclient, "windowAjouterclient");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label13, "label13");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, button10, "button10");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, label16, "label16");
  GLADE_HOOKUP_OBJECT (windowAjouterclient, button8, "button8");

  return windowAjouterclient;
}

GtkWidget*
create_windowModifierclient (void)
{
  GtkWidget *windowModifierclient;
  GtkWidget *fixed3;
  GtkWidget *fixed4;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *entry9;
  GtkWidget *label22;
  GtkWidget *entry10;
  GtkWidget *label23;
  GtkWidget *entry11;
  GtkWidget *label24;
  GtkWidget *entry12;
  GtkWidget *label25;
  GtkWidget *label29;
  GtkWidget *label26;
  GtkWidget *button12;
  GtkWidget *button13;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label27;

  windowModifierclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowModifierclient), _("Modifier Client"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowModifierclient), fixed3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_fixed_put (GTK_FIXED (fixed3), fixed4, 0, 0);
  gtk_widget_set_size_request (fixed4, 0, 0);

  spinbutton4_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton4, 696, 272);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton5, 760, 272);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1900, 1900, 2019, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton6, 824, 272);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 584, 208);
  gtk_widget_set_size_request (entry7, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 584, 240);
  gtk_widget_set_size_request (entry8, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label20 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 440, 240);
  gtk_widget_set_size_request (label20, 106, 25);

  label21 = gtk_label_new (_("Date de naissance (jj/mm/aaaa)"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 440, 272);
  gtk_widget_set_size_request (label21, 262, 28);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9, 584, 304);
  gtk_widget_set_size_request (entry9, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label22 = gtk_label_new (_("Nom_utilisateur"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 440, 304);
  gtk_widget_set_size_request (label22, 162, 27);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed4), entry10, 584, 336);
  gtk_widget_set_size_request (entry10, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label23 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 440, 336);
  gtk_widget_set_size_request (label23, 142, 30);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed4), entry11, 584, 368);
  gtk_widget_set_size_request (entry11, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  label24 = gtk_label_new (_("Confirmer"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 440, 368);
  gtk_widget_set_size_request (label24, 121, 30);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 584, 400);
  gtk_widget_set_size_request (entry12, 298, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  label25 = gtk_label_new (_("CIN"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 440, 400);
  gtk_widget_set_size_request (label25, 77, 30);

  label29 = gtk_label_new (_("Nom client "));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 448, 208);
  gtk_widget_set_size_request (label29, 111, 25);

  label26 = gtk_label_new (_("Modifier un client"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 648, 152);
  gtk_widget_set_size_request (label26, 140, 27);

  button12 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed4), button12, 584, 440);
  gtk_widget_set_size_request (button12, 100, 30);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed4), button13, 464, 96);
  gtk_widget_set_size_request (button13, 98, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button13), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox9), label27, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_modifier_modifier_client_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_retour_modifier_client_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifierclient, windowModifierclient, "windowModifierclient");
  GLADE_HOOKUP_OBJECT (windowModifierclient, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowModifierclient, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowModifierclient, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (windowModifierclient, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (windowModifierclient, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (windowModifierclient, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (windowModifierclient, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label20, "label20");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label21, "label21");
  GLADE_HOOKUP_OBJECT (windowModifierclient, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label22, "label22");
  GLADE_HOOKUP_OBJECT (windowModifierclient, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label23, "label23");
  GLADE_HOOKUP_OBJECT (windowModifierclient, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowModifierclient, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label25, "label25");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label26, "label26");
  GLADE_HOOKUP_OBJECT (windowModifierclient, button12, "button12");
  GLADE_HOOKUP_OBJECT (windowModifierclient, button13, "button13");
  GLADE_HOOKUP_OBJECT (windowModifierclient, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowModifierclient, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowModifierclient, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowModifierclient, label27, "label27");

  return windowModifierclient;
}

GtkWidget*
create_windowreserverexcursionadmin (void)
{
  GtkWidget *windowreserverexcursionadmin;
  GtkWidget *fixed7;
  GtkWidget *fixed8;
  GtkWidget *treeview2;
  GtkWidget *hbuttonbox2;
  GtkWidget *entry14;
  GtkWidget *button30;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *button28;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label55;
  GtkWidget *button29;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label51;
  GtkWidget *button27;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label49;
  GtkWidget *button31;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label54;

  windowreserverexcursionadmin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowreserverexcursionadmin), _("Reserver excursions (admin/agent)"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (windowreserverexcursionadmin), fixed7);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed8, 0, 0);
  gtk_widget_set_size_request (fixed8, 0, 0);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview2, 344, 184);
  gtk_widget_set_size_request (treeview2, 494, 265);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_fixed_put (GTK_FIXED (fixed8), hbuttonbox2, 640, 432);
  gtk_widget_set_size_request (hbuttonbox2, 255, 29);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed8), entry14, 672, 120);
  gtk_widget_set_size_request (entry14, 169, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  button30 = gtk_button_new ();
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed8), button30, 704, 88);
  gtk_widget_set_size_request (button30, 100, 30);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button30), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox28), label52, FALSE, FALSE, 0);

  label53 = gtk_label_new (_("Excursions :"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed8), label53, 296, 136);
  gtk_widget_set_size_request (label53, 176, 37);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed8), button28, 544, 472);
  gtk_widget_set_size_request (button28, 100, 30);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button28), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox30), label55, FALSE, FALSE, 0);

  button29 = gtk_button_new ();
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed8), button29, 680, 472);
  gtk_widget_set_size_request (button29, 100, 30);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button29), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox27), label51, FALSE, FALSE, 0);

  button27 = gtk_button_new ();
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed8), button27, 408, 472);
  gtk_widget_set_size_request (button27, 100, 30);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button27), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox25), label49, FALSE, FALSE, 0);

  button31 = gtk_button_new ();
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed8), button31, 344, 48);
  gtk_widget_set_size_request (button31, 100, 30);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button31), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox29), label54, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button30, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button28, "clicked",
                    G_CALLBACK (on_reserver_reserver_excursion_a_clicked),
                    NULL);
  g_signal_connect ((gpointer) button29, "clicked",
                    G_CALLBACK (on_supprimer_reserver_excursion_a_clicked),
                    NULL);
  g_signal_connect ((gpointer) button27, "clicked",
                    G_CALLBACK (on_Ajouter_reserver_excursion_a_clicked),
                    NULL);
  g_signal_connect ((gpointer) button31, "clicked",
                    G_CALLBACK (on_retour_reserver_excursion_a_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowreserverexcursionadmin, windowreserverexcursionadmin, "windowreserverexcursionadmin");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, button30, "button30");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, image28, "image28");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, label52, "label52");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, label53, "label53");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, button28, "button28");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, image30, "image30");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, label55, "label55");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, button29, "button29");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, image27, "image27");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, label51, "label51");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, button27, "button27");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, image25, "image25");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, label49, "label49");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, button31, "button31");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, image29, "image29");
  GLADE_HOOKUP_OBJECT (windowreserverexcursionadmin, label54, "label54");

  return windowreserverexcursionadmin;
}

GtkWidget*
create_windowreserverexcursion_client (void)
{
  GtkWidget *windowreserverexcursion_client;
  GtkWidget *fixed9;
  GtkWidget *fixed10;
  GtkWidget *treeview3;
  GtkWidget *hbuttonbox3;
  GtkWidget *entry15;
  GtkWidget *button33;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image32;
  GtkWidget *label57;
  GtkWidget *label61;
  GtkWidget *button34;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image33;
  GtkWidget *label58;
  GtkWidget *button35;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image34;
  GtkWidget *label59;

  windowreserverexcursion_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowreserverexcursion_client), _("reserver excursion  (Client)"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (windowreserverexcursion_client), fixed9);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed9), fixed10, 0, 0);
  gtk_widget_set_size_request (fixed10, 0, 0);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview3, 344, 184);
  gtk_widget_set_size_request (treeview3, 494, 265);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_fixed_put (GTK_FIXED (fixed10), hbuttonbox3, 640, 432);
  gtk_widget_set_size_request (hbuttonbox3, 255, 29);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed10), entry15, 672, 120);
  gtk_widget_set_size_request (entry15, 169, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  button33 = gtk_button_new ();
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed10), button33, 704, 88);
  gtk_widget_set_size_request (button33, 100, 30);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (button33), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image32 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox32), image32, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox32), label57, FALSE, FALSE, 0);

  label61 = gtk_label_new (_("Excursions :"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed10), label61, 296, 136);
  gtk_widget_set_size_request (label61, 176, 37);

  button34 = gtk_button_new ();
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed10), button34, 344, 48);
  gtk_widget_set_size_request (button34, 100, 30);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (button34), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image33 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox33), image33, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox33), label58, FALSE, FALSE, 0);

  button35 = gtk_button_new ();
  gtk_widget_show (button35);
  gtk_fixed_put (GTK_FIXED (fixed10), button35, 536, 472);
  gtk_widget_set_size_request (button35, 100, 30);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (button35), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image34 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox34), image34, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox34), label59, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button33, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button34, "clicked",
                    G_CALLBACK (on_retour_reserver_excursion_c_clicked),
                    NULL);
  g_signal_connect ((gpointer) button35, "clicked",
                    G_CALLBACK (on_reserver_reserver_excursion_c_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowreserverexcursion_client, windowreserverexcursion_client, "windowreserverexcursion_client");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, button33, "button33");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, image32, "image32");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, label57, "label57");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, label61, "label61");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, button34, "button34");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, image33, "image33");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, label58, "label58");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, button35, "button35");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, image34, "image34");
  GLADE_HOOKUP_OBJECT (windowreserverexcursion_client, label59, "label59");

  return windowreserverexcursion_client;
}

